-- 000003_create_legacy_user_table.up.sql
-- Table: public."user" (Legacy user reference table for foreign keys)

CREATE TABLE IF NOT EXISTS public."user" (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(125),
    password VARCHAR(125),
    perusahaan VARCHAR(125),
    role VARCHAR(125),
    id_perusahaan BIGINT REFERENCES public.perusahaan(id_perusahaan) ON DELETE SET NULL
);
