-- 000002_create_perusahaan_table.up.sql
-- Table: public.perusahaan (Tenant / Company Directory)

CREATE TABLE IF NOT EXISTS public.perusahaan (
    id_perusahaan BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_perusahaan VARCHAR(125)
);

CREATE INDEX IF NOT EXISTS idx_perusahaan_nama ON public.perusahaan (nama_perusahaan);
