-- ==========================================================
-- QTERA Mandiri & POC AI - Database Complete Initialization
-- PostgreSQL 14+ / 18+
-- Generated from db.sql and system architecture specs
-- ==========================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE SCHEMA IF NOT EXISTS schema1;

-- 1. Perusahaan (Company / Multi-tenant Directory)
CREATE TABLE IF NOT EXISTS public.perusahaan (
    id_perusahaan BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_perusahaan VARCHAR(125) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_perusahaan_nama ON public.perusahaan (nama_perusahaan);

-- 2. Legacy User Table (Referenced by chat FK)
CREATE TABLE IF NOT EXISTS public."user" (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(125),
    password VARCHAR(125),
    perusahaan VARCHAR(125),
    role VARCHAR(125),
    id_perusahaan BIGINT REFERENCES public.perusahaan(id_perusahaan) ON DELETE SET NULL
);

-- 3. Users Table (Core Auth & Session Management)
CREATE TABLE IF NOT EXISTS public.users (
    id TEXT PRIMARY KEY,
    username TEXT NOT NULL CONSTRAINT users_username_key UNIQUE,
    email TEXT NOT NULL CONSTRAINT users_email_key UNIQUE,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'operator',
    company TEXT DEFAULT '',
    id_perusahaan BIGINT REFERENCES public.perusahaan(id_perusahaan) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_users_username ON public.users (username);
CREATE INDEX IF NOT EXISTS idx_users_email ON public.users (email);
CREATE INDEX IF NOT EXISTS idx_users_id_perusahaan ON public.users (id_perusahaan);

-- 4. Assets Table (IT Hardware / Equipment Catalog)
CREATE TABLE IF NOT EXISTS public.assets (
    asset_id VARCHAR(125) CONSTRAINT "assets_Asset_ID_not_null" NOT NULL,
    name VARCHAR(125),
    category VARCHAR(125),
    brand VARCHAR(125),
    model_type VARCHAR(125),
    purchase_date VARCHAR(125),
    purchase_price VARCHAR(125),
    location VARCHAR(125),
    created_at VARCHAR(125),
    perusahaan VARCHAR(125),
    status VARCHAR(125),
    CONSTRAINT assets_pkey PRIMARY KEY (asset_id)
);
CREATE INDEX IF NOT EXISTS idx_assets_perusahaan ON public.assets (perusahaan);
CREATE INDEX IF NOT EXISTS idx_assets_category ON public.assets (category);
CREATE INDEX IF NOT EXISTS idx_assets_brand ON public.assets (brand);
CREATE INDEX IF NOT EXISTS idx_assets_location ON public.assets (location);
CREATE INDEX IF NOT EXISTS idx_assets_status ON public.assets (status);

-- 5. Chat Table (Audit trail, conversational memory, and attachments)
CREATE TABLE IF NOT EXISTS public.chat (
    id VARCHAR(125) CONSTRAINT chat_chat_id_not_null NOT NULL,
    "user" BOOLEAN,
    chat TEXT,
    created_at VARCHAR(125),
    user_id BIGINT,
    username VARCHAR(125),
    role VARCHAR(125),
    models VARCHAR(125),
    attachment_name VARCHAR(255),
    attachment_url TEXT,
    attachment_type VARCHAR(100),
    attachment_size BIGINT,
    attachment_text TEXT,
    CONSTRAINT chat_pkey PRIMARY KEY (id),
    CONSTRAINT fk_chat_user_id FOREIGN KEY (user_id) REFERENCES public."user"(user_id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_chat_username ON public.chat (username);
CREATE INDEX IF NOT EXISTS idx_chat_created_at ON public.chat (created_at);

-- 6. Schedule Table (Routine Inspection and Audit Scheduling)
CREATE TABLE IF NOT EXISTS public.schedule (
    id_schedule UUID DEFAULT gen_random_uuid() NOT NULL,
    category VARCHAR(125),
    start VARCHAR(125),
    frequency VARCHAR(125),
    CONSTRAINT schedule_pkey PRIMARY KEY (id_schedule)
);
CREATE INDEX IF NOT EXISTS idx_schedule_category ON public.schedule (category);
CREATE INDEX IF NOT EXISTS idx_schedule_start ON public.schedule (start);

-- 7. Tools History Table (Agentic Tool Execution Logs)
CREATE TABLE IF NOT EXISTS public.tools_history (
    id TEXT NOT NULL,
    perusahaan TEXT DEFAULT '' NOT NULL,
    tools TEXT DEFAULT '' NOT NULL,
    created_by_user_id TEXT DEFAULT '',
    created_by_username TEXT DEFAULT '',
    created_by_role TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    CONSTRAINT tools_history_pkey PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_tools_history_perusahaan ON public.tools_history (perusahaan);
CREATE INDEX IF NOT EXISTS idx_tools_history_created_at ON public.tools_history (created_at);

-- 8. Groups Table (Agentic groups / teams)
CREATE TABLE IF NOT EXISTS public.groups (
    id TEXT PRIMARY KEY,
    perusahaan TEXT DEFAULT '',
    group_name TEXT NOT NULL,
    application TEXT DEFAULT '',
    agent_id TEXT DEFAULT '',
    created_by_user_id TEXT DEFAULT '',
    created_by_username TEXT DEFAULT '',
    created_by_role TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_groups_perusahaan ON public.groups (perusahaan);
CREATE INDEX IF NOT EXISTS idx_groups_name ON public.groups (group_name);

-- 9. AI Registration Sessions & Drafts
CREATE TABLE IF NOT EXISTS public.ai_registration_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id TEXT NOT NULL,
    source_file_url TEXT,
    raw_text TEXT,
    status VARCHAR(50) NOT NULL DEFAULT 'processing',
    reject_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_ai_reg_sessions_user_id ON public.ai_registration_sessions (user_id);

CREATE TABLE IF NOT EXISTS public.ai_registration_drafts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id UUID NOT NULL REFERENCES public.ai_registration_sessions(id) ON DELETE CASCADE,
    sequence_no INT NOT NULL DEFAULT 1,
    fields JSONB NOT NULL DEFAULT '{}'::jsonb,
    status VARCHAR(50) NOT NULL DEFAULT 'pending',
    created_asset_id VARCHAR(125),
    low_confidence BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_ai_reg_drafts_session_id ON public.ai_registration_drafts (session_id);
