package controllers

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/gofiber/fiber/v2"
	"golang-dh/middleware"
)

// AnomalyThresholds defines configurable limits for detecting transaction anomalies per tenant
type AnomalyThresholds struct {
	CompanyName         string `json:"company_name,omitempty"`
	MaxDurationDays     int    `json:"max_duration_days"`     // default 28: > 28 hari (Sinyal 1)
	MaxActiveLoans      int    `json:"max_active_loans"`      // default 3:  >= 3 pinjaman aktif (Sinyal 2)
	MaxLateReturns      int    `json:"max_late_returns"`      // default 2:  >= 2 telat kembali dalam 6 bulan (Sinyal 3)
	MaxExtensions       int    `json:"max_extensions"`        // default 2:  >= 2 perpanjangan dalam 6 bulan (Sinyal 4)
	MaxAssetCount       int    `json:"max_asset_count"`       // default 5:  > 5 aset dalam 1 permohonan (Sinyal 5)
	AuditWindowDays     int    `json:"audit_window_days"`     // default 7:  <= 7 hari sebelum audit (Sinyal 6)
	RepeatBorrowCycles  int    `json:"repeat_borrow_cycles"`  // default 2:  >= 2 kali pinjam aset sama (Sinyal 7)
	MinSignalsForReview int    `json:"min_signals_for_review"`// default 1:  >= 1 sinyal terpicu = review
}

var (
	anomalyThresholdsLock sync.RWMutex
	fallbackDefaultThresholds = AnomalyThresholds{
		CompanyName:         "qtera mandiri",
		MaxDurationDays:     getIntEnv("ANOMALY_MAX_DURATION_DAYS", 28),
		MaxActiveLoans:      getIntEnv("ANOMALY_MAX_ACTIVE_LOANS", 3),
		MaxLateReturns:      getIntEnv("ANOMALY_MAX_LATE_RETURNS", 2),
		MaxExtensions:       getIntEnv("ANOMALY_MAX_EXTENSIONS", 2),
		MaxAssetCount:       getIntEnv("ANOMALY_MAX_ASSET_COUNT", 5),
		AuditWindowDays:     getIntEnv("ANOMALY_AUDIT_WINDOW_DAYS", 7),
		RepeatBorrowCycles:  getIntEnv("ANOMALY_REPEAT_BORROW_CYCLES", 2),
		MinSignalsForReview: getIntEnv("ANOMALY_MIN_SIGNALS", 1),
	}
)

func getIntEnv(key string, fallback int) int {
	if val := os.Getenv(key); val != "" {
		if parsed, err := strconv.Atoi(strings.TrimSpace(val)); err == nil && parsed > 0 {
			return parsed
		}
	}
	return fallback
}

// EnsureBorrowThresholdSettingsTable creates the public.borrow_threshold_settings table,
// adds an automatic trigger to seed default thresholds whenever a new perusahaan is added,
// and seeds records for existing tenants.
func EnsureBorrowThresholdSettingsTable(ctx context.Context) error {
	if DB == nil {
		return fmt.Errorf("database connection pool is not initialized")
	}

	createTableSQL := `
	CREATE TABLE IF NOT EXISTS public.perusahaan (
		id_perusahaan BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		nama_perusahaan VARCHAR(125)
	);

	CREATE TABLE IF NOT EXISTS public.borrow_threshold_settings (
		id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
		company_name VARCHAR(125) NOT NULL UNIQUE,
		max_duration_days INT NOT NULL DEFAULT 28,
		max_active_loans INT NOT NULL DEFAULT 3,
		max_late_returns INT NOT NULL DEFAULT 2,
		max_extensions INT NOT NULL DEFAULT 2,
		max_asset_count INT NOT NULL DEFAULT 5,
		audit_window_days INT NOT NULL DEFAULT 7,
		repeat_borrow_cycles INT NOT NULL DEFAULT 2,
		min_signals_for_review INT NOT NULL DEFAULT 1,
		created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
		updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
	);

	CREATE OR REPLACE FUNCTION trg_auto_create_borrow_thresholds()
	RETURNS TRIGGER AS $$
	BEGIN
		INSERT INTO public.borrow_threshold_settings (company_name)
		VALUES (NEW.nama_perusahaan)
		ON CONFLICT (company_name) DO NOTHING;
		RETURN NEW;
	END;
	$$ LANGUAGE plpgsql;

	DROP TRIGGER IF EXISTS trg_perusahaan_insert_thresholds ON public.perusahaan;
	CREATE TRIGGER trg_perusahaan_insert_thresholds
	AFTER INSERT ON public.perusahaan
	FOR EACH ROW
	EXECUTE FUNCTION trg_auto_create_borrow_thresholds();

	INSERT INTO public.borrow_threshold_settings (company_name)
	SELECT DISTINCT nama_perusahaan FROM public.perusahaan 
	WHERE nama_perusahaan IS NOT NULL AND TRIM(nama_perusahaan) != ''
	ON CONFLICT (company_name) DO NOTHING;

	INSERT INTO public.borrow_threshold_settings (company_name)
	VALUES ('qtera mandiri')
	ON CONFLICT (company_name) DO NOTHING;
	`

	_, err := DB.Exec(ctx, createTableSQL)
	if err != nil {
		log.Printf("[EnsureBorrowThresholdSettingsTable] Failed to bootstrap public.borrow_threshold_settings: %v", err)
		return err
	}
	log.Println("[EnsureBorrowThresholdSettingsTable] Table public.borrow_threshold_settings and auto-creation trigger verified successfully.")
	return nil
}

// ResolveTenantCompany resolves the company / tenant name for the current request
func ResolveTenantCompany(c *fiber.Ctx) string {
	company := ""
	if id := middleware.RequestIdentity(c); id != nil {
		company = strings.TrimSpace(id.Company)
		if company == "" && id.IdPerusahaan > 0 && DB != nil {
			_ = DB.QueryRow(c.Context(), `SELECT nama_perusahaan FROM public.perusahaan WHERE id_perusahaan = $1 LIMIT 1`, id.IdPerusahaan).Scan(&company)
		}
	}
	if company == "" {
		company = strings.TrimSpace(c.Get("X-Company"))
	}
	if company == "" {
		company = strings.TrimSpace(c.Get("X-Company-Name"))
	}
	if company == "" {
		company = strings.TrimSpace(c.Get("X-Tenant-ID"))
	}
	if company == "" {
		company = strings.TrimSpace(c.Query("group_name"))
	}
	if company == "" {
		company = strings.TrimSpace(c.Query("company"))
	}
	if company == "" {
		company = "qtera mandiri"
	}
	return company
}

// GetTenantThresholds retrieves anomaly thresholds from the DB for a given tenant,
// automatically seeding default thresholds if the tenant does not exist yet.
func GetTenantThresholds(ctx context.Context, company string) AnomalyThresholds {
	company = strings.TrimSpace(company)
	if company == "" {
		company = "qtera mandiri"
	}

	defaultCfg := fallbackDefaultThresholds
	defaultCfg.CompanyName = company

	if DB == nil {
		return defaultCfg
	}

	var matchedCompany string
	err := DB.QueryRow(ctx, `SELECT company_name FROM public.borrow_threshold_settings WHERE LOWER(TRIM(company_name)) = LOWER(TRIM($1)) LIMIT 1`, company).Scan(&matchedCompany)
	if err == nil && matchedCompany != "" {
		company = matchedCompany
	} else {
		// Automatically create default settings row for this tenant
		_, _ = DB.Exec(ctx, `
			INSERT INTO public.borrow_threshold_settings (company_name)
			VALUES ($1)
			ON CONFLICT (company_name) DO NOTHING
		`, company)
	}

	row := DB.QueryRow(ctx, `
		SELECT company_name, max_duration_days, max_active_loans, max_late_returns,
		       max_extensions, max_asset_count, audit_window_days, repeat_borrow_cycles, min_signals_for_review
		FROM public.borrow_threshold_settings
		WHERE LOWER(TRIM(company_name)) = LOWER(TRIM($1))
		LIMIT 1
	`, company)

	var res AnomalyThresholds
	if err := row.Scan(
		&res.CompanyName,
		&res.MaxDurationDays,
		&res.MaxActiveLoans,
		&res.MaxLateReturns,
		&res.MaxExtensions,
		&res.MaxAssetCount,
		&res.AuditWindowDays,
		&res.RepeatBorrowCycles,
		&res.MinSignalsForReview,
	); err != nil {
		return defaultCfg
	}

	return res
}

// UpdateTenantThresholds updates the threshold values for a specific tenant in the database
func UpdateTenantThresholds(ctx context.Context, company string, newCfg AnomalyThresholds) (AnomalyThresholds, error) {
	company = strings.TrimSpace(company)
	if company == "" {
		company = "qtera mandiri"
	}

	curr := GetTenantThresholds(ctx, company)
	if newCfg.MaxDurationDays > 0 {
		curr.MaxDurationDays = newCfg.MaxDurationDays
	}
	if newCfg.MaxActiveLoans > 0 {
		curr.MaxActiveLoans = newCfg.MaxActiveLoans
	}
	if newCfg.MaxLateReturns > 0 {
		curr.MaxLateReturns = newCfg.MaxLateReturns
	}
	if newCfg.MaxExtensions > 0 {
		curr.MaxExtensions = newCfg.MaxExtensions
	}
	if newCfg.MaxAssetCount > 0 {
		curr.MaxAssetCount = newCfg.MaxAssetCount
	}
	if newCfg.AuditWindowDays > 0 {
		curr.AuditWindowDays = newCfg.AuditWindowDays
	}
	if newCfg.RepeatBorrowCycles > 0 {
		curr.RepeatBorrowCycles = newCfg.RepeatBorrowCycles
	}
	if newCfg.MinSignalsForReview > 0 {
		curr.MinSignalsForReview = newCfg.MinSignalsForReview
	}

	if DB == nil {
		return curr, fmt.Errorf("database connection pool is not initialized")
	}

	_, err := DB.Exec(ctx, `
		INSERT INTO public.borrow_threshold_settings (
			company_name, max_duration_days, max_active_loans, max_late_returns,
			max_extensions, max_asset_count, audit_window_days, repeat_borrow_cycles,
			min_signals_for_review, updated_at
		) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, NOW())
		ON CONFLICT (company_name) DO UPDATE SET
			max_duration_days = EXCLUDED.max_duration_days,
			max_active_loans = EXCLUDED.max_active_loans,
			max_late_returns = EXCLUDED.max_late_returns,
			max_extensions = EXCLUDED.max_extensions,
			max_asset_count = EXCLUDED.max_asset_count,
			audit_window_days = EXCLUDED.audit_window_days,
			repeat_borrow_cycles = EXCLUDED.repeat_borrow_cycles,
			min_signals_for_review = EXCLUDED.min_signals_for_review,
			updated_at = NOW()
	`, curr.CompanyName, curr.MaxDurationDays, curr.MaxActiveLoans, curr.MaxLateReturns,
		curr.MaxExtensions, curr.MaxAssetCount, curr.AuditWindowDays,
		curr.RepeatBorrowCycles, curr.MinSignalsForReview)

	if err != nil {
		return curr, err
	}
	return curr, nil
}

// GetAnomalyThresholdsConfig returns a copy of active anomaly thresholds (fallback)
func GetAnomalyThresholdsConfig() AnomalyThresholds {
	return GetTenantThresholds(context.Background(), "qtera mandiri")
}

// SetAnomalyThresholdsConfig updates the active anomaly thresholds (fallback)
func SetAnomalyThresholdsConfig(newCfg AnomalyThresholds) AnomalyThresholds {
	updated, _ := UpdateTenantThresholds(context.Background(), "qtera mandiri", newCfg)
	return updated
}

// GetAnomalySettings handles GET /api/borrow/anomalies/settings
func GetAnomalySettings(c *fiber.Ctx) error {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	tenant := ResolveTenantCompany(c)
	settings := GetTenantThresholds(ctx, tenant)
	return c.JSON(fiber.Map{
		"tenant":   tenant,
		"settings": settings,
	})
}

// UpdateAnomalySettings handles POST /api/borrow/anomalies/settings
func UpdateAnomalySettings(c *fiber.Ctx) error {
	role := ""
	if id := middleware.RequestIdentity(c); id != nil {
		role = strings.ToLower(strings.TrimSpace(id.Role))
	}
	if role == "" {
		role = strings.ToLower(strings.TrimSpace(c.Get("X-User-Role")))
	}
	if role == "" {
		role = strings.ToLower(strings.TrimSpace(c.Get("X-Role")))
	}
	if role == "" {
		role = strings.ToLower(strings.TrimSpace(c.Query("role")))
	}

	if role != "admin" {
		return c.Status(403).JSON(fiber.Map{
			"error": "Akses ditolak: Hanya pengguna dengan role Administrator yang diizinkan untuk mengubah konfigurasi dan threshold peminjaman.",
		})
	}

	var payload AnomalyThresholds
	if err := c.BodyParser(&payload); err != nil {
		return c.Status(400).JSON(fiber.Map{"error": "Format payload tidak valid"})
	}

	tenant := strings.TrimSpace(payload.CompanyName)
	if tenant == "" {
		tenant = ResolveTenantCompany(c)
	}

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	updated, err := UpdateTenantThresholds(ctx, tenant, payload)
	if err != nil {
		return c.Status(500).JSON(fiber.Map{"error": "Gagal menyimpan threshold ke database: " + err.Error()})
	}

	return c.JSON(fiber.Map{
		"message":  fmt.Sprintf("Pengaturan threshold peminjaman untuk tenant '%s' berhasil diperbarui", tenant),
		"tenant":   tenant,
		"settings": updated,
	})
}


// BorrowApprovalItem represents an item in an approval transaction
type BorrowApprovalItem struct {
	ID                   string  `json:"id"`
	TransactionID        string  `json:"transaction_id"`
	AssetID              string  `json:"asset_id"`
	AssetName            string  `json:"asset_name"`
	Brand                string  `json:"brand"`
	ModelType            string  `json:"model_type"`
	Category             string  `json:"category"`
	DurationDays         int     `json:"duration_days"`
	ApprovedDurationDays *int    `json:"approved_duration_days"`
	Note                 *string `json:"note"`
	IsApproved           *bool   `json:"is_approved"`
	Status               string  `json:"status"`
}

// BorrowApprovalTransaction represents header + items for approval
type BorrowApprovalTransaction struct {
	ID              string               `json:"id"`
	TransactionCode string               `json:"transaction_code"`
	BorrowerID      string               `json:"borrower_id"`
	BorrowerName    string               `json:"borrower_name"`
	ManagerID       string               `json:"manager_id"`
	ManagerName     string               `json:"manager_name"`
	GroupName       string               `json:"group_name"`
	RequestDate     time.Time            `json:"request_date"`
	Status          string               `json:"status"`
	ItemCount       int                  `json:"item_count"`
	Items           []BorrowApprovalItem `json:"items,omitempty"`
}

// AnomalyContextItem represents a metric comparison
type AnomalyContextItem struct {
	Metric   string `json:"metric"`
	GroupVal int    `json:"group_val"`
	TotalVal int    `json:"total_val"`
	Status   string `json:"status"` // "normal" or "menonjol"
}

// AnomalySignal represents a single detected anomaly signal
type AnomalySignal struct {
	ID          int    `json:"id"`
	Name        string `json:"name"`
	Triggered   bool   `json:"triggered"`
	Description string `json:"description"`
}

// AnomalyReportResponse is the response format for Check Anomalies
type AnomalyReportResponse struct {
	DataAsOf          string               `json:"data_as_of"`
	TransactionCode   string               `json:"transaction_code"`
	BorrowerName      string               `json:"borrower_name"`
	GroupName         string               `json:"group_name"`
	BorrowerContext   []AnomalyContextItem `json:"borrower_context"`
	RequestContext    []AnomalySignal      `json:"request_context"`
	SignalsCount      int                  `json:"signals_count"`
	ReviewRecommended bool                 `json:"review_recommended"`
	Thresholds        *AnomalyThresholds   `json:"thresholds,omitempty"`
	Narrative         string               `json:"narrative"`
	ErrorMessage      string               `json:"error_message,omitempty"`
	IsAIGenerated     bool                 `json:"is_ai_generated"`
}

// GetBorrowApprovals handles GET /api/borrow/approvals
func GetBorrowApprovals(c *fiber.Ctx) error {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	_, userCompany := resolveUserContext(c)
	if userCompany == "" {
		userCompany = strings.TrimSpace(c.Get("X-Company"))
	}

	// group_name is the user division/department, only filter if explicitly passed as query param
	groupName := strings.TrimSpace(c.Query("group_name"))
	borrowerID := strings.TrimSpace(c.Query("borrower_id"))
	if borrowerID == "" {
		borrowerID = strings.TrimSpace(c.Get("X-User-ID"))
	}
	role := strings.ToLower(strings.TrimSpace(c.Query("role")))
	if role == "" {
		role = strings.ToLower(strings.TrimSpace(c.Get("X-Role")))
	}
	if role == "" {
		role = strings.ToLower(strings.TrimSpace(c.Get("X-User-Role")))
	}
	if role == "" {
		if id := middleware.RequestIdentity(c); id != nil && id.Role != "" {
			role = strings.ToLower(strings.TrimSpace(id.Role))
		}
	}

	query := `
		SELECT t.id, t.transaction_code, t.borrower_id, t.borrower_name, 
		       COALESCE(t.manager_id, ''), t.manager_name, t.group_name, 
		       t.request_date, t.status, COUNT(DISTINCT i.id) AS item_count
		FROM public.borrow_transactions t
		LEFT JOIN public.borrow_items i ON t.id = i.transaction_id
		LEFT JOIN public.assets a ON i.asset_id = a.asset_id
		LEFT JOIN public.users u ON (t.borrower_id = u.id OR LOWER(t.borrower_name) = LOWER(u.username))
		WHERE t.status != 'rejected'
	`
	var args []any
	argIdx := 1

	// Strict Tenant Isolation: only show approvals belonging to the authenticated tenant/company
	if userCompany != "" {
		query += fmt.Sprintf(` AND (
			LOWER(TRIM(u.company)) = LOWER(TRIM($%d))
			OR LOWER(TRIM(t.group_name)) = LOWER(TRIM($%d))
		)`, argIdx, argIdx)
		args = append(args, userCompany)
		argIdx++
	}

	// Group filter (division)
	if groupName != "" {
		query += fmt.Sprintf(" AND LOWER(t.group_name) = LOWER($%d)", argIdx)
		args = append(args, groupName)
		argIdx++
	}

	// Role scoping: non-admin only sees their own transactions
	if role != "admin" && borrowerID != "" {
		query += fmt.Sprintf(" AND (t.borrower_id = $%d OR LOWER(t.borrower_name) = LOWER($%d))", argIdx, argIdx)
		args = append(args, borrowerID)
		argIdx++
	}

	query += `
		GROUP BY t.id, t.transaction_code, t.borrower_id, t.borrower_name, 
		         t.manager_id, t.manager_name, t.group_name, t.request_date, t.status
		ORDER BY t.request_date DESC
	`

	rows, err := DB.Query(ctx, query, args...)
	if err != nil {
		return c.Status(500).JSON(fiber.Map{"error": err.Error()})
	}
	defer rows.Close()

	result := []BorrowApprovalTransaction{}
	for rows.Next() {
		var item BorrowApprovalTransaction
		if err := rows.Scan(
			&item.ID, &item.TransactionCode, &item.BorrowerID, &item.BorrowerName,
			&item.ManagerID, &item.ManagerName, &item.GroupName,
			&item.RequestDate, &item.Status, &item.ItemCount,
		); err != nil {
			return c.Status(500).JSON(fiber.Map{"error": err.Error()})
		}
		result = append(result, item)
	}

	return c.JSON(fiber.Map{"transactions": result})
}

// BorrowHistoryRecommendation represents aggregated recommendation data based on past borrow transactions
type BorrowHistoryRecommendation struct {
	AssetName             string   `json:"asset_name"`
	Category              string   `json:"category"`
	ModelType             string   `json:"model_type"`
	Brand                 string   `json:"brand"`
	BorrowCount           int      `json:"borrow_count"`
	DistinctBorrowers     int      `json:"distinct_borrowers"`
	AvgDurationDays       int      `json:"avg_duration_days"`
	LastBorrowedDate      string   `json:"last_borrowed_date"`
	RecommendationReason  string   `json:"recommendation_reason"`
	AvailableUnitsCount   int      `json:"available_units_count"`
	AvailableAssetSamples []string `json:"available_asset_samples"`
}

// GetBorrowHistoryRecommendations handles GET /api/borrow/history/recommendations
func GetBorrowHistoryRecommendations(c *fiber.Ctx) error {
	ctx, cancel := context.WithTimeout(context.Background(), 8*time.Second)
	defer cancel()

	_, userCompany := resolveUserContext(c)
	if userCompany == "" {
		userCompany = strings.TrimSpace(c.Get("X-Company"))
	}

	searchQuery := strings.TrimSpace(c.Query("query"))
	if searchQuery == "" {
		searchQuery = strings.TrimSpace(c.Query("keyword"))
	}
	category := strings.TrimSpace(c.Query("category"))
	location := strings.TrimSpace(c.Query("location"))
	groupName := strings.TrimSpace(c.Query("group_name"))

	limit := 5
	if l := c.Query("limit"); l != "" {
		if val, err := strconv.Atoi(l); err == nil && val > 0 && val <= 20 {
			limit = val
		}
	}

	var args []any
	argIdx := 1

	sqlQuery := `
		SELECT 
			MAX(COALESCE(a.name, i.asset_id)) AS asset_name,
			MAX(COALESCE(a.category, '')) AS category,
			MAX(COALESCE(a.model_type, '')) AS model_type,
			MAX(COALESCE(a.brand, '')) AS brand,
			COUNT(i.id) AS borrow_count,
			COUNT(DISTINCT t.borrower_id) AS distinct_borrowers,
			ROUND(AVG(COALESCE(i.duration_days, 14)))::int AS avg_duration_days,
			COALESCE(TO_CHAR(MAX(t.request_date), 'YYYY-MM-DD"T"HH24:MI:SSOF'), '') AS last_borrowed_date
		FROM public.borrow_items i
		JOIN public.borrow_transactions t ON i.transaction_id = t.id
		LEFT JOIN public.assets a ON i.asset_id = a.asset_id
		LEFT JOIN public.users u ON (t.borrower_id = u.id OR LOWER(t.borrower_name) = LOWER(u.username))
		WHERE t.status != 'rejected'
	`

	if userCompany != "" {
		sqlQuery += fmt.Sprintf(` AND (
			LOWER(TRIM(u.company)) = LOWER(TRIM($%d))
			OR LOWER(TRIM(t.group_name)) = LOWER(TRIM($%d))
			OR LOWER(TRIM(a.perusahaan)) = LOWER(TRIM($%d))
			OR EXISTS (
				SELECT 1 FROM public.perusahaan p
				WHERE (LOWER(TRIM(p.nama_perusahaan)) = LOWER(TRIM($%d)) OR p.id_perusahaan::text = LOWER(TRIM($%d)))
				  AND (a.perusahaan = p.id_perusahaan::text OR LOWER(TRIM(a.perusahaan)) = LOWER(TRIM(p.nama_perusahaan)) OR u.company = p.id_perusahaan::text OR LOWER(TRIM(u.company)) = LOWER(TRIM(p.nama_perusahaan)))
			)
		)`, argIdx, argIdx, argIdx, argIdx, argIdx)
		args = append(args, userCompany)
		argIdx++
	}

	if groupName != "" {
		sqlQuery += fmt.Sprintf(" AND LOWER(t.group_name) ILIKE '%%' || LOWER($%d) || '%%'", argIdx)
		args = append(args, groupName)
		argIdx++
	}

	if category != "" {
		sqlQuery += fmt.Sprintf(" AND LOWER(a.category) ILIKE '%%' || LOWER($%d) || '%%'", argIdx)
		args = append(args, category)
		argIdx++
	}

	if location != "" {
		sqlQuery += fmt.Sprintf(" AND LOWER(a.location) ILIKE '%%' || LOWER($%d) || '%%'", argIdx)
		args = append(args, location)
		argIdx++
	}

	if searchQuery != "" {
		sqlQuery += fmt.Sprintf(` AND (
			LOWER(a.name) ILIKE '%%' || LOWER($%d) || '%%'
			OR LOWER(a.category) ILIKE '%%' || LOWER($%d) || '%%'
			OR LOWER(a.model_type) ILIKE '%%' || LOWER($%d) || '%%'
			OR LOWER(a.brand) ILIKE '%%' || LOWER($%d) || '%%'
			OR LOWER(a.location) ILIKE '%%' || LOWER($%d) || '%%'
			OR LOWER(t.group_name) ILIKE '%%' || LOWER($%d) || '%%'
		)`, argIdx, argIdx, argIdx, argIdx, argIdx, argIdx)
		args = append(args, searchQuery)
		argIdx++
	}

	sqlQuery += fmt.Sprintf(`
		GROUP BY LOWER(TRIM(COALESCE(a.name, i.asset_id)))
		ORDER BY borrow_count DESC, MAX(t.request_date) DESC
		LIMIT $%d
	`, argIdx)
	args = append(args, limit)

	rows, err := DB.Query(ctx, sqlQuery, args...)
	if err != nil {
		return c.Status(500).JSON(fiber.Map{"error": err.Error()})
	}
	defer rows.Close()

	var recs []BorrowHistoryRecommendation

	for rows.Next() {
		var r BorrowHistoryRecommendation
		if err := rows.Scan(
			&r.AssetName, &r.Category, &r.ModelType, &r.Brand,
			&r.BorrowCount, &r.DistinctBorrowers, &r.AvgDurationDays, &r.LastBorrowedDate,
		); err != nil {
			continue
		}

		r.RecommendationReason = fmt.Sprintf("Paling sering dipinjam dalam riwayat transaksi (%d kali dipinjam oleh %d peminjam berbeda)", r.BorrowCount, r.DistinctBorrowers)

		// Query available stock for this asset name so the AI can provide immediate ready-to-borrow asset_ids
		stockQuery := `
			SELECT a.asset_id 
			FROM public.assets a
			WHERE LOWER(a.name) = LOWER($1) 
			  AND LOWER(COALESCE(a.status, 'available')) IN ('available', 'active')
		`
		stockArgs := []any{r.AssetName}
		if userCompany != "" {
			stockQuery += ` AND (
				LOWER(TRIM(a.perusahaan)) = LOWER(TRIM($2))
				OR EXISTS (
					SELECT 1 FROM public.perusahaan p
					WHERE (LOWER(TRIM(p.nama_perusahaan)) = LOWER(TRIM($2)) OR p.id_perusahaan::text = LOWER(TRIM($2)))
					  AND (a.perusahaan = p.id_perusahaan::text OR LOWER(TRIM(a.perusahaan)) = LOWER(TRIM(p.nama_perusahaan)))
				)
			)`
			stockArgs = append(stockArgs, userCompany)
		}
		stockQuery += " LIMIT 10"

		stockRows, stockErr := DB.Query(ctx, stockQuery, stockArgs...)
		if stockErr == nil {
			var samples []string
			for stockRows.Next() {
				var sID string
				if errS := stockRows.Scan(&sID); errS == nil && sID != "" {
					samples = append(samples, sID)
				}
			}
			stockRows.Close()
			r.AvailableAssetSamples = samples
			r.AvailableUnitsCount = len(samples)
		}

		recs = append(recs, r)
	}

	// Fallback to active inventory if no borrow history exists yet for this query
	if len(recs) == 0 && (searchQuery != "" || category != "" || location != "") {
		fallbackQuery := `
			SELECT 
				MAX(a.name) AS asset_name,
				MAX(COALESCE(a.category, '')) AS category,
				MAX(COALESCE(a.model_type, '')) AS model_type,
				MAX(COALESCE(a.brand, '')) AS brand,
				0 AS borrow_count,
				0 AS distinct_borrowers,
				14 AS avg_duration_days,
				'' AS last_borrowed_date,
				COUNT(a.id) AS available_count
			FROM public.assets a
			WHERE LOWER(COALESCE(a.status, 'available')) IN ('available', 'active')
		`
		fbArgs := []any{}
		fbIdx := 1
		if userCompany != "" {
			fallbackQuery += fmt.Sprintf(` AND (
				LOWER(TRIM(a.perusahaan)) = LOWER(TRIM($%d))
				OR EXISTS (
					SELECT 1 FROM public.perusahaan p
					WHERE (LOWER(TRIM(p.nama_perusahaan)) = LOWER(TRIM($%d)) OR p.id_perusahaan::text = LOWER(TRIM($%d)))
					  AND (a.perusahaan = p.id_perusahaan::text OR LOWER(TRIM(a.perusahaan)) = LOWER(TRIM(p.nama_perusahaan)))
				)
			)`, fbIdx, fbIdx, fbIdx)
			fbArgs = append(fbArgs, userCompany)
			fbIdx++
		}
		if searchQuery != "" {
			fallbackQuery += fmt.Sprintf(` AND (
				LOWER(a.name) ILIKE '%%' || LOWER($%d) || '%%'
				OR LOWER(a.category) ILIKE '%%' || LOWER($%d) || '%%'
				OR LOWER(a.model_type) ILIKE '%%' || LOWER($%d) || '%%'
				OR LOWER(a.location) ILIKE '%%' || LOWER($%d) || '%%'
			)`, fbIdx, fbIdx, fbIdx, fbIdx)
			fbArgs = append(fbArgs, searchQuery)
			fbIdx++
		}
		fallbackQuery += fmt.Sprintf(`
			GROUP BY LOWER(TRIM(a.name))
			ORDER BY available_count DESC
			LIMIT $%d
		`, fbIdx)
		fbArgs = append(fbArgs, limit)

		fbRows, fbErr := DB.Query(ctx, fallbackQuery, fbArgs...)
		if fbErr == nil {
			defer fbRows.Close()
			for fbRows.Next() {
				var r BorrowHistoryRecommendation
				var availCount int
				if errFb := fbRows.Scan(
					&r.AssetName, &r.Category, &r.ModelType, &r.Brand,
					&r.BorrowCount, &r.DistinctBorrowers, &r.AvgDurationDays, &r.LastBorrowedDate,
					&availCount,
				); errFb == nil {
					r.RecommendationReason = fmt.Sprintf("Belum ada riwayat peminjaman untuk kategori ini. Direkomendasikan berdasarkan ketersediaan unit aktif di inventaris (%d unit tersedia)", availCount)
					r.AvailableUnitsCount = availCount
					recs = append(recs, r)
				}
			}
		}
	}

	if recs == nil {
		recs = []BorrowHistoryRecommendation{}
	}

	return c.JSON(fiber.Map{
		"recommendations": recs,
		"total":           len(recs),
		"search_criteria": fiber.Map{
			"query":    searchQuery,
			"category": category,
			"location": location,
			"company":  userCompany,
		},
	})
}

// GetBorrowTransaction handles GET /api/borrow/:id
func GetBorrowTransaction(c *fiber.Ctx) error {
	idParam := c.Params("id")
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	var trx BorrowApprovalTransaction
	err := DB.QueryRow(ctx, `
		SELECT id, transaction_code, borrower_id, borrower_name, 
		       COALESCE(manager_id, ''), manager_name, group_name, 
		       request_date, status
		FROM public.borrow_transactions
		WHERE id::text = $1 OR transaction_code = $1
	`, idParam).Scan(
		&trx.ID, &trx.TransactionCode, &trx.BorrowerID, &trx.BorrowerName,
		&trx.ManagerID, &trx.ManagerName, &trx.GroupName,
		&trx.RequestDate, &trx.Status,
	)
	if err != nil {
		return c.Status(404).JSON(fiber.Map{"error": "Transaction not found"})
	}

	// Tenant boundary check: transaction belongs to userCompany if u.company == userCompany OR trx.GroupName == userCompany
	reqCompany := strings.TrimSpace(c.Get("X-Company"))
	if _, uComp := resolveUserContext(c); uComp != "" {
		reqCompany = uComp
	}
	if reqCompany != "" {
		var borrowerCompany string
		_ = DB.QueryRow(ctx, `SELECT COALESCE(company, '') FROM public.users WHERE id::text = $1 OR LOWER(username) = LOWER($2) LIMIT 1`, trx.BorrowerID, trx.BorrowerName).Scan(&borrowerCompany)

		matches := false
		if borrowerCompany != "" && strings.EqualFold(borrowerCompany, reqCompany) {
			matches = true
		} else if trx.GroupName != "" && strings.EqualFold(trx.GroupName, reqCompany) {
			matches = true
		}

		if !matches && (borrowerCompany != "" || trx.GroupName != "") {
			return c.Status(403).JSON(fiber.Map{"error": "Access denied to transaction from another company"})
		}
	}

	// Role scoping: non-admin can only access their own transaction
	role := strings.ToLower(strings.TrimSpace(c.Query("role")))
	if role == "" {
		role = strings.ToLower(strings.TrimSpace(c.Get("X-Role")))
	}
	borrowerID := strings.TrimSpace(c.Query("borrower_id"))
	if borrowerID == "" {
		borrowerID = strings.TrimSpace(c.Get("X-User-ID"))
	}
	if role != "admin" && borrowerID != "" {
		if trx.BorrowerID != borrowerID && !strings.EqualFold(trx.BorrowerName, borrowerID) {
			return c.Status(403).JSON(fiber.Map{"error": "Access denied to this transaction"})
		}
	}

	rows, err := DB.Query(ctx, `
		SELECT i.id, i.transaction_id, i.asset_id, COALESCE(a.name, ''), 
		       COALESCE(a.brand, ''), COALESCE(a.model_type, ''), COALESCE(a.category, ''),
		       i.duration_days, i.approved_duration_days, i.note, i.is_approved, i.status
		FROM public.borrow_items i
		LEFT JOIN public.assets a ON i.asset_id = a.asset_id
		WHERE i.transaction_id = $1
	`, trx.ID)
	if err == nil {
		defer rows.Close()
		for rows.Next() {
			var itm BorrowApprovalItem
			_ = rows.Scan(
				&itm.ID, &itm.TransactionID, &itm.AssetID, &itm.AssetName,
				&itm.Brand, &itm.ModelType, &itm.Category,
				&itm.DurationDays, &itm.ApprovedDurationDays, &itm.Note, &itm.IsApproved, &itm.Status,
			)
			trx.Items = append(trx.Items, itm)
		}
	}
	trx.ItemCount = len(trx.Items)

	return c.JSON(trx)
}

// CheckBorrowAnomalies handles GET /api/borrow/:id/anomalies
func CheckBorrowAnomalies(c *fiber.Ctx) error {
	idParam := c.Params("id")
	ctx, cancel := context.WithTimeout(context.Background(), 40*time.Second)
	defer cancel()

	// 1. Get Transaction Info
	var trx BorrowApprovalTransaction
	err := DB.QueryRow(ctx, `
		SELECT id, transaction_code, borrower_id, borrower_name, group_name, request_date
		FROM public.borrow_transactions
		WHERE id::text = $1 OR transaction_code = $1
	`, idParam).Scan(
		&trx.ID, &trx.TransactionCode, &trx.BorrowerID, &trx.BorrowerName, &trx.GroupName, &trx.RequestDate,
	)
	if err != nil {
		return c.Status(404).JSON(fiber.Map{"error": "Transaction not found"})
	}

	// 2. Fetch Items
	rows, err := DB.Query(ctx, `
		SELECT i.id, i.asset_id, COALESCE(a.name, ''), COALESCE(a.category, ''), i.duration_days
		FROM public.borrow_items i
		LEFT JOIN public.assets a ON i.asset_id = a.asset_id
		WHERE i.transaction_id = $1
	`, trx.ID)
	if err != nil {
		return c.Status(500).JSON(fiber.Map{"error": err.Error()})
	}
	defer rows.Close()

	type itemDetail struct {
		AssetID      string
		AssetName    string
		Category     string
		DurationDays int
	}
	var items []itemDetail
	for rows.Next() {
		var itm itemDetail
		var dummyID string
		_ = rows.Scan(&dummyID, &itm.AssetID, &itm.AssetName, &itm.Category, &itm.DurationDays)
		items = append(items, itm)
	}

	// 3. Compute 7 Signals using tenant-specific thresholds from database
	tenantName := strings.TrimSpace(trx.GroupName)
	if tenantName == "" {
		tenantName = ResolveTenantCompany(c)
	}
	cfg := GetTenantThresholds(ctx, tenantName)

	// Optional query overrides per request (e.g. ?max_duration_days=30&max_active_loans=5)
	if qDur := c.Query("max_duration_days"); qDur != "" {
		if v, err := strconv.Atoi(qDur); err == nil && v > 0 {
			cfg.MaxDurationDays = v
		}
	}
	if qAct := c.Query("max_active_loans"); qAct != "" {
		if v, err := strconv.Atoi(qAct); err == nil && v > 0 {
			cfg.MaxActiveLoans = v
		}
	}
	if qLate := c.Query("max_late_returns"); qLate != "" {
		if v, err := strconv.Atoi(qLate); err == nil && v > 0 {
			cfg.MaxLateReturns = v
		}
	}
	if qExt := c.Query("max_extensions"); qExt != "" {
		if v, err := strconv.Atoi(qExt); err == nil && v > 0 {
			cfg.MaxExtensions = v
		}
	}
	if qCount := c.Query("max_asset_count"); qCount != "" {
		if v, err := strconv.Atoi(qCount); err == nil && v > 0 {
			cfg.MaxAssetCount = v
		}
	}
	if qAudit := c.Query("audit_window_days"); qAudit != "" {
		if v, err := strconv.Atoi(qAudit); err == nil && v > 0 {
			cfg.AuditWindowDays = v
		}
	}
	if qRep := c.Query("repeat_borrow_cycles"); qRep != "" {
		if v, err := strconv.Atoi(qRep); err == nil && v > 0 {
			cfg.RepeatBorrowCycles = v
		}
	}
	if qMin := c.Query("min_signals_for_review"); qMin != "" {
		if v, err := strconv.Atoi(qMin); err == nil && v > 0 {
			cfg.MinSignalsForReview = v
		}
	}

	var triggeredSignals []string
	var allSignals []AnomalySignal

	// Sinyal 1: Durasi tiap aset vs kebiasaan kategori (Ambang: > cfg.MaxDurationDays)
	s1Triggered := false
	s1Desc := "Durasi request sesuai batas normal kebiasaan kategori aset."
	for _, it := range items {
		if it.DurationDays > cfg.MaxDurationDays {
			s1Triggered = true
			s1Desc = fmt.Sprintf("Durasi pinjam (%d hari) melampaui batas kebiasaan kategori %s (> %d hari).", it.DurationDays, it.Category, cfg.MaxDurationDays)
			triggeredSignals = append(triggeredSignals, s1Desc)
			break
		}
	}
	allSignals = append(allSignals, AnomalySignal{
		ID:          1,
		Name:        "Durasi tiap aset vs kebiasaan kategori",
		Triggered:   s1Triggered,
		Description: s1Desc,
	})

	// Sinyal 2: Pinjaman aktif peminjam (Group ini & Total)
	var activeLoansGroup, activeLoansTotal int
	_ = DB.QueryRow(ctx, `
		SELECT COUNT(DISTINCT t.id)
		FROM public.borrow_transactions t
		WHERE t.borrower_id = $1 AND t.status = 'active' AND t.group_name = $2
	`, trx.BorrowerID, trx.GroupName).Scan(&activeLoansGroup)

	_ = DB.QueryRow(ctx, `
		SELECT COUNT(DISTINCT t.id)
		FROM public.borrow_transactions t
		WHERE t.borrower_id = $1 AND t.status = 'active'
	`, trx.BorrowerID).Scan(&activeLoansTotal)

	s2Triggered := activeLoansTotal >= cfg.MaxActiveLoans
	s2Desc := fmt.Sprintf("Peminjam saat ini memegang %d pinjaman aktif.", activeLoansTotal)
	if s2Triggered {
		s2Desc = fmt.Sprintf("Peminjam memiliki %d pinjaman aktif sekaligus (ambang batas >= %d).", activeLoansTotal, cfg.MaxActiveLoans)
		triggeredSignals = append(triggeredSignals, s2Desc)
	}
	allSignals = append(allSignals, AnomalySignal{
		ID:          2,
		Name:        "Pinjaman aktif peminjam",
		Triggered:   s2Triggered,
		Description: s2Desc,
	})

	// Sinyal 3: Telat kembali (6 bulan terakhir)
	var lateReturnsGroup, lateReturnsTotal int
	_ = DB.QueryRow(ctx, `
		SELECT COUNT(DISTINCT t.id)
		FROM public.borrow_transactions t
		JOIN public.borrow_items i ON t.id = i.transaction_id
		WHERE t.borrower_id = $1 AND t.group_name = $2
		  AND i.returned_at > i.due_date
		  AND i.returned_at >= NOW() - INTERVAL '6 months'
	`, trx.BorrowerID, trx.GroupName).Scan(&lateReturnsGroup)

	_ = DB.QueryRow(ctx, `
		SELECT COUNT(DISTINCT t.id)
		FROM public.borrow_transactions t
		JOIN public.borrow_items i ON t.id = i.transaction_id
		WHERE t.borrower_id = $1
		  AND i.returned_at > i.due_date
		  AND i.returned_at >= NOW() - INTERVAL '6 months'
	`, trx.BorrowerID).Scan(&lateReturnsTotal)

	s3Triggered := lateReturnsTotal >= cfg.MaxLateReturns
	s3Desc := fmt.Sprintf("Keterlambatan pengembalian: %d kali dalam 6 bulan.", lateReturnsTotal)
	if s3Triggered {
		s3Desc = fmt.Sprintf("Peminjam tercatat %d kali terlambat mengembalikan aset dalam 6 bulan terakhir (ambang batas >= %d).", lateReturnsTotal, cfg.MaxLateReturns)
		triggeredSignals = append(triggeredSignals, s3Desc)
	}
	allSignals = append(allSignals, AnomalySignal{
		ID:          3,
		Name:        "Telat kembali (6 bulan terakhir)",
		Triggered:   s3Triggered,
		Description: s3Desc,
	})

	// Sinyal 4: Sering perpanjangan (6 bulan terakhir)
	var extGroup, extTotal int
	_ = DB.QueryRow(ctx, `
		SELECT COUNT(e.id)
		FROM public.borrow_extensions e
		JOIN public.borrow_transactions t ON e.transaction_id = t.id
		WHERE e.borrower_id = $1 AND t.group_name = $2
		  AND e.request_date >= NOW() - INTERVAL '6 months'
	`, trx.BorrowerID, trx.GroupName).Scan(&extGroup)

	_ = DB.QueryRow(ctx, `
		SELECT COUNT(id)
		FROM public.borrow_extensions
		WHERE borrower_id = $1 AND request_date >= NOW() - INTERVAL '6 months'
	`, trx.BorrowerID).Scan(&extTotal)

	s4Triggered := extTotal >= cfg.MaxExtensions
	s4Desc := fmt.Sprintf("Pengajuan perpanjangan: %d kali dalam 6 bulan.", extTotal)
	if s4Triggered {
		s4Desc = fmt.Sprintf("Peminjam telah mengajukan perpanjangan durasi %d kali dalam 6 bulan terakhir (ambang batas >= %d).", extTotal, cfg.MaxExtensions)
		triggeredSignals = append(triggeredSignals, s4Desc)
	}
	allSignals = append(allSignals, AnomalySignal{
		ID:          4,
		Name:        "Sering perpanjangan",
		Triggered:   s4Triggered,
		Description: s4Desc,
	})

	// Sinyal 5: Jumlah aset per request (> cfg.MaxAssetCount aset)
	s5Triggered := len(items) > cfg.MaxAssetCount
	s5Desc := fmt.Sprintf("Jumlah aset dalam permohonan: %d aset.", len(items))
	if s5Triggered {
		s5Desc = fmt.Sprintf("Jumlah aset yang diajukan (%d aset) melebihi batas kebiasaan transaksi (> %d aset).", len(items), cfg.MaxAssetCount)
		triggeredSignals = append(triggeredSignals, s5Desc)
	}
	allSignals = append(allSignals, AnomalySignal{
		ID:          5,
		Name:        "Jumlah aset per request vs kebiasaan",
		Triggered:   s5Triggered,
		Description: s5Desc,
	})

	// Sinyal 6: Menghindari jadwal Audit (rentang cfg.AuditWindowDays hari sebelum jadwal audit mulai)
	s6Triggered := false
	s6Desc := fmt.Sprintf("Tidak terdeteksi jadwal audit dalam rentang %d hari ke depan.", cfg.AuditWindowDays)
	var auditCategory string
	var auditStartDate time.Time
	auditIntervalStr := fmt.Sprintf("%d days", cfg.AuditWindowDays)
	errAudit := DB.QueryRow(ctx, `
		SELECT category, TO_DATE(start, 'YYYY-MM-DD')
		FROM public.schedule
		WHERE group_name = $1
		  AND TO_DATE(start, 'YYYY-MM-DD') >= $2::date
		  AND TO_DATE(start, 'YYYY-MM-DD') <= ($2::date + $3::interval)
		ORDER BY TO_DATE(start, 'YYYY-MM-DD') ASC
		LIMIT 1
	`, trx.GroupName, trx.RequestDate, auditIntervalStr).Scan(&auditCategory, &auditStartDate)

	if errAudit == nil {
		s6Triggered = true
		diffDays := int(auditStartDate.Sub(trx.RequestDate).Hours() / 24)
		if diffDays < 0 {
			diffDays = 0
		}
		s6Desc = fmt.Sprintf("Permohonan diajukan mepet (%d hari sebelum) jadwal %s pada %s.", diffDays, auditCategory, auditStartDate.Format("02 Jan 2006"))
		triggeredSignals = append(triggeredSignals, s6Desc)
	}
	allSignals = append(allSignals, AnomalySignal{
		ID:          6,
		Name:        "Menghindari jadwal Audit",
		Triggered:   s6Triggered,
		Description: s6Desc,
	})

	// Sinyal 7: Pinjam ulang berturut-turut (aset sama, orang sama, cycleCount >= cfg.RepeatBorrowCycles)
	s7Triggered := false
	s7Desc := "Tidak ada riwayat perputaran pinjam-kembalikan berulang jarak dekat."
	for _, it := range items {
		var cycleCount int
		_ = DB.QueryRow(ctx, `
			SELECT COUNT(DISTINCT t.id)
			FROM public.borrow_transactions t
			JOIN public.borrow_items i ON t.id = i.transaction_id
			WHERE t.borrower_id = $1 AND i.asset_id = $2
			  AND t.status = 'completed'
			  AND i.returned_at >= NOW() - INTERVAL '6 months'
		`, trx.BorrowerID, it.AssetID).Scan(&cycleCount)

		if cycleCount >= cfg.RepeatBorrowCycles {
			s7Triggered = true
			s7Desc = fmt.Sprintf("Aset '%s' memiliki siklus berulang pinjam-kembalikan-pinjam lagi oleh peminjam ini (%d kali dalam 6 bulan, ambang batas >= %d).", it.AssetName, cycleCount, cfg.RepeatBorrowCycles)
			triggeredSignals = append(triggeredSignals, s7Desc)
			break
		}
	}
	allSignals = append(allSignals, AnomalySignal{
		ID:          7,
		Name:        "Pinjam ulang berturut-turut",
		Triggered:   s7Triggered,
		Description: s7Desc,
	})

	// 4. Build Borrower Context Summary
	borrowerContext := []AnomalyContextItem{
		{
			Metric:   "Pinjaman aktif",
			GroupVal: activeLoansGroup,
			TotalVal: activeLoansTotal,
			Status:   statusLabel(s2Triggered),
		},
		{
			Metric:   "Telat kembali (6 bulan terakhir)",
			GroupVal: lateReturnsGroup,
			TotalVal: lateReturnsTotal,
			Status:   statusLabel(s3Triggered),
		},
		{
			Metric:   "Jumlah pengajuan perpanjangan (6 bulan terakhir)",
			GroupVal: extGroup,
			TotalVal: extTotal,
			Status:   statusLabel(s4Triggered),
		},
	}

	signalsCount := len(triggeredSignals)
	reviewRecommended := signalsCount >= cfg.MinSignalsForReview

	// 5. Generate Narrative (AI Synthesizer or Empty/Error without placeholder fallback)
	narrative := ""
	errorMessage := ""
	isAI := false
	if signalsCount > 0 {
		log.Printf("[borrow_anomaly] Requesting AI narrative from eiai_go for %s (%d signals)...", trx.BorrowerName, signalsCount)
		aiNarrative, errAI := synthesizeNarrativeWithAI(trx.BorrowerName, trx.GroupName, triggeredSignals)
		if errAI != nil {
			log.Printf("[borrow_anomaly] AI narrative error: %v", errAI)
			errorMessage = errAI.Error()
		} else {
			log.Printf("[borrow_anomaly] Received AI narrative: %s", aiNarrative)
			narrative = aiNarrative
			isAI = true
		}
	}

	response := AnomalyReportResponse{
		DataAsOf:          time.Now().Format("02 Jan 2006 15:04:05 WIB"),
		TransactionCode:   trx.TransactionCode,
		BorrowerName:      trx.BorrowerName,
		GroupName:         trx.GroupName,
		BorrowerContext:   borrowerContext,
		RequestContext:    allSignals,
		SignalsCount:      signalsCount,
		ReviewRecommended: reviewRecommended,
		Thresholds:        &cfg,
		Narrative:         narrative,
		ErrorMessage:      errorMessage,
		IsAIGenerated:     isAI,
	}

	return c.JSON(response)
}

func statusLabel(triggered bool) string {
	if triggered {
		return "menonjol"
	}
	return "normal"
}

// synthesizeNarrativeWithAI calls eiai_go service to synthesize a flowing narrative
func synthesizeNarrativeWithAI(borrowerName, groupName string, signals []string) (string, error) {
	eiaiURL := os.Getenv("EIAI_URL")
	if eiaiURL == "" {
		eiaiURL = "http://127.0.0.1:8000"
	}
	baseURL := strings.TrimRight(eiaiURL, "/")
	if strings.HasSuffix(baseURL, "/rag") {
		baseURL = strings.TrimSuffix(baseURL, "/rag")
	}

	payload := map[string]interface{}{
		"borrower_name": borrowerName,
		"group_name":    groupName,
		"signals":       signals,
	}

	bodyBytes, _ := json.Marshal(payload)
	req, err := http.NewRequest("POST", baseURL+"/anomaly/narrative", bytes.NewBuffer(bodyBytes))
	if err != nil {
		return "", err
	}
	req.Header.Set("Content-Type", "application/json")

	client := &http.Client{Timeout: 35 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		respBody, _ := io.ReadAll(resp.Body)
		return "", fmt.Errorf("EIAI error %d: %s", resp.StatusCode, string(respBody))
	}

	var res struct {
		Narrative string `json:"narrative"`
		Error     string `json:"error"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&res); err != nil {
		return "", err
	}
	if res.Error != "" {
		return "", fmt.Errorf("%s", res.Error)
	}

	return strings.TrimSpace(res.Narrative), nil
}

// ApproveBorrowTransaction handles POST /api/borrow/:id/approve
func ApproveBorrowTransaction(c *fiber.Ctx) error {
	idParam := c.Params("id")
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	type ItemDecision struct {
		ID                   string  `json:"id"`
		ApprovedDurationDays *int    `json:"approved_duration_days"`
		Note                 *string `json:"note"`
		IsApproved           *bool   `json:"is_approved"`
	}

	var payload struct {
		Decision string         `json:"decision"` // "approve" or "reject"
		Items    []ItemDecision `json:"items"`
	}

	if err := c.BodyParser(&payload); err != nil {
		return c.Status(400).JSON(fiber.Map{"error": "Invalid request body"})
	}

	for _, itm := range payload.Items {
		itemStatus := "approved"
		if itm.IsApproved != nil && !*itm.IsApproved {
			itemStatus = "rejected"
		}
		_, _ = DB.Exec(ctx, `
			UPDATE public.borrow_items
			SET approved_duration_days = $1, note = $2, is_approved = $3, status = $4
			WHERE id::text = $5
		`, itm.ApprovedDurationDays, itm.Note, itm.IsApproved, itemStatus, itm.ID)
	}

	if payload.Decision == "reject" {
		// Ditolak: Hapus dari borrow_items dan borrow_transactions agar tidak memenuhi halaman
		var trxUUID string
		_ = DB.QueryRow(ctx, `SELECT id FROM public.borrow_transactions WHERE id::text = $1 OR transaction_code = $1 LIMIT 1`, idParam).Scan(&trxUUID)
		if trxUUID != "" {
			_, _ = DB.Exec(ctx, `DELETE FROM public.borrow_items WHERE transaction_id = $1`, trxUUID)
			_, _ = DB.Exec(ctx, `DELETE FROM public.borrow_transactions WHERE id = $1`, trxUUID)
		} else {
			_, _ = DB.Exec(ctx, `DELETE FROM public.borrow_transactions WHERE id::text = $1 OR transaction_code = $1`, idParam)
		}
		return c.JSON(fiber.Map{"message": "Transaksi berhasil ditolak dan dihapus", "status": "deleted"})
	}

	overallStatus := "approved"
	_, err := DB.Exec(ctx, `
		UPDATE public.borrow_transactions
		SET status = $1
		WHERE id::text = $2 OR transaction_code = $2
	`, overallStatus, idParam)
	if err != nil {
		return c.Status(500).JSON(fiber.Map{"error": err.Error()})
	}

	// Update asset status to 'borrowed' for approved items in public.assets
	var trxUUID string
	_ = DB.QueryRow(ctx, `SELECT id FROM public.borrow_transactions WHERE id::text = $1 OR transaction_code = $1 LIMIT 1`, idParam).Scan(&trxUUID)
	if trxUUID != "" {
		_, _ = DB.Exec(ctx, `
			UPDATE public.assets
			SET status = 'borrowed'
			WHERE asset_id IN (
				SELECT asset_id FROM public.borrow_items
				WHERE transaction_id = $1 AND COALESCE(status, 'approved') != 'rejected'
			)
		`, trxUUID)
	}

	return c.JSON(fiber.Map{"message": "Transaction approval processed successfully", "status": overallStatus})
}

// ResolveUserByBorrowerName searches public.users to get the exact users.id (LIMIT 1).
func ResolveUserByBorrowerName(ctx context.Context, name string) (userID, username, company string, found bool) {
	name = strings.TrimSpace(name)
	if name == "" {
		return "", "", "", false
	}

	// 1. Direct exact match on username or email in public.users
	err := DB.QueryRow(ctx, `
		SELECT id, username, COALESCE(company, '') 
		FROM public.users 
		WHERE LOWER(TRIM(username)) = LOWER(TRIM($1)) OR LOWER(TRIM(email)) = LOWER(TRIM($1))
		LIMIT 1
	`, name).Scan(&userID, &username, &company)
	if err == nil && userID != "" {
		return userID, username, company, true
	}

	// 2. Token-based matching: split string into words (e.g. "sasori dan tordalk" -> "sasori", "tordalk")
	tokens := strings.FieldsFunc(name, func(r rune) bool {
		return r == ' ' || r == ',' || r == ';' || r == '/' || r == '\\' || r == '&' || r == '-' || r == '_'
	})
	noiseWords := map[string]bool{
		"dan": true, "and": true, "atau": true, "or": true, "untuk": true, "for": true,
		"si": true, "ke": true, "di": true, "dari": true, "with": true, "dengan": true,
		"yg": true, "yang": true, "pada": true,
	}
	for _, tok := range tokens {
		tokClean := strings.ToLower(strings.Trim(tok, " \t\r\n,.;:!?'\"()[]{}"))
		if len(tokClean) < 2 || noiseWords[tokClean] {
			continue
		}
		err = DB.QueryRow(ctx, `
			SELECT id, username, COALESCE(company, '') 
			FROM public.users 
			WHERE LOWER(TRIM(username)) = LOWER(TRIM($1)) OR LOWER(TRIM(email)) = LOWER(TRIM($1))
			LIMIT 1
		`, tokClean).Scan(&userID, &username, &company)
		if err == nil && userID != "" {
			return userID, username, company, true
		}
	}

	// 3. Reverse substring match ($1 ILIKE '%' || username || '%') and substring match
	err = DB.QueryRow(ctx, `
		SELECT id, username, COALESCE(company, '') 
		FROM public.users 
		WHERE $1 ILIKE '%' || username || '%' OR username ILIKE '%' || $1 || '%'
		ORDER BY 
			CASE 
				WHEN LOWER(TRIM(username)) = LOWER(TRIM($1)) THEN 1
				WHEN $1 ILIKE '%' || username || '%' THEN 2
				ELSE 3
			END, 
			LENGTH(username) DESC
		LIMIT 1
	`, name).Scan(&userID, &username, &company)
	if err == nil && userID != "" {
		return userID, username, company, true
	}

	// 4. Token substring in public.users
	for _, tok := range tokens {
		tokClean := strings.ToLower(strings.Trim(tok, " \t\r\n,.;:!?'\"()[]{}"))
		if len(tokClean) < 3 || noiseWords[tokClean] {
			continue
		}
		err = DB.QueryRow(ctx, `
			SELECT id, username, COALESCE(company, '') 
			FROM public.users 
			WHERE username ILIKE '%' || $1 || '%'
			ORDER BY LENGTH(username) ASC
			LIMIT 1
		`, tokClean).Scan(&userID, &username, &company)
		if err == nil && userID != "" {
			return userID, username, company, true
		}
	}

	// 5. Try legacy public."user" table
	var legacyUID any
	var legacyName, legacyPerusahaan string
	err = DB.QueryRow(ctx, `
		SELECT user_id, COALESCE(name, ''), COALESCE(perusahaan, '') 
		FROM public."user" 
		WHERE $1 ILIKE '%' || name || '%' OR name ILIKE '%' || $1 || '%'
		ORDER BY LENGTH(name) DESC
		LIMIT 1
	`, name).Scan(&legacyUID, &legacyName, &legacyPerusahaan)
	if err == nil && legacyUID != nil {
		return fmt.Sprintf("%v", legacyUID), legacyName, legacyPerusahaan, true
	}

	// 6. Try previous borrow_transactions where borrower_id is a UUID or exists in public.users
	var priorID, priorName, priorGroup string
	err = DB.QueryRow(ctx, `
		SELECT b.borrower_id, b.borrower_name, COALESCE(b.group_name, '')
		FROM public.borrow_transactions b
		WHERE (b.borrower_name ILIKE '%' || $1 || '%' OR $1 ILIKE '%' || b.borrower_name || '%')
		  AND b.borrower_id IS NOT NULL 
		  AND b.borrower_id != ''
		  AND b.borrower_id != b.borrower_name
		ORDER BY b.created_at DESC
		LIMIT 1
	`, name).Scan(&priorID, &priorName, &priorGroup)
	if err == nil && priorID != "" {
		return priorID, priorName, priorGroup, true
	}

	// 7. Fallback to first registered user in public.users so borrower_id is ALWAYS a valid users.id
	var defaultID, defaultUsername, defaultCompany string
	err = DB.QueryRow(ctx, `
		SELECT id, username, COALESCE(company, '') 
		FROM public.users 
		ORDER BY created_at ASC 
		LIMIT 1
	`).Scan(&defaultID, &defaultUsername, &defaultCompany)
	if err == nil && defaultID != "" {
		log.Printf("[ResolveUserByBorrowerName] No direct user match for '%s', resolved fallback users.id=%s (username=%s)", name, defaultID, defaultUsername)
		return defaultID, name, defaultCompany, false
	}

	return "", name, "", false
}

// LookupUserByName finds a user / borrower ID from the database based on username, email, or name (LIMIT 1).
func LookupUserByName(c *fiber.Ctx) error {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	name := strings.TrimSpace(c.Query("name"))
	if name == "" {
		name = strings.TrimSpace(c.Query("username"))
	}
	if name == "" {
		name = strings.TrimSpace(c.Query("borrower_name"))
	}
	if name == "" {
		return c.Status(400).JSON(fiber.Map{"error": "name parameter is required"})
	}

	userID, username, company, _ := ResolveUserByBorrowerName(ctx, name)

	return c.JSON(fiber.Map{
		"user_id":  userID,
		"username": username,
		"company":  company,
	})
}

// CreateBorrowRequest handles POST /api/borrow/request
func CreateBorrowRequest(c *fiber.Ctx) error {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	type ReqItem struct {
		AssetID      string `json:"asset_id"`
		DurationDays int    `json:"duration_days"`
	}

	var payload struct {
		BorrowerID   string    `json:"borrower_id"`
		BorrowerName string    `json:"borrower_name"`
		GroupName    string    `json:"group_name"`
		ManagerID    string    `json:"manager_id"`
		ManagerName  string    `json:"manager_name"`
		Items        []ReqItem `json:"items"`
	}

	if err := c.BodyParser(&payload); err != nil {
		return c.Status(400).JSON(fiber.Map{"error": "Invalid request body"})
	}

	if strings.TrimSpace(payload.BorrowerName) == "" && strings.TrimSpace(payload.BorrowerID) == "" {
		return c.Status(400).JSON(fiber.Map{"error": "Nama peminjam atau borrower_id wajib diisi"})
	}
	if len(payload.Items) == 0 {
		return c.Status(400).JSON(fiber.Map{"error": "Minimal 1 aset harus dipilih"})
	}

	// 1. Manager credentials resolution
	if strings.TrimSpace(payload.ManagerID) == "" {
		if id := middleware.RequestIdentity(c); id != nil && id.UserID != "" {
			payload.ManagerID = id.UserID
		} else if uid := c.Get("X-User-ID"); uid != "" {
			payload.ManagerID = uid
		}
	}
	if strings.TrimSpace(payload.ManagerName) == "" {
		if id := middleware.RequestIdentity(c); id != nil && id.Username != "" {
			payload.ManagerName = id.Username
		} else if uname := c.Get("X-User-Name"); uname != "" {
			payload.ManagerName = uname
		} else if uname := c.Get("X-Username"); uname != "" {
			payload.ManagerName = uname
		} else if payload.ManagerID != "" {
			payload.ManagerName = payload.ManagerID
		}
	}

	// 2. Borrower resolution: Fetch borrower_id from DB based on borrower_name (take 1)
	if strings.TrimSpace(payload.BorrowerName) == "" && strings.TrimSpace(payload.BorrowerID) != "" {
		payload.BorrowerName = payload.BorrowerID
	}
	if strings.TrimSpace(payload.BorrowerName) != "" {
		bName := strings.TrimSpace(payload.BorrowerName)
		uID, uName, uCompany, found := ResolveUserByBorrowerName(ctx, bName)
		if uID != "" {
			payload.BorrowerID = uID
			if found && uName != "" {
				payload.BorrowerName = uName
			}
			if uCompany != "" && (payload.GroupName == "" || payload.GroupName == "qtera mandiri") {
				payload.GroupName = uCompany
			}
			log.Printf("[CreateBorrowRequest] Resolved borrower_id=%s (users.id) for borrower_name=%s", payload.BorrowerID, payload.BorrowerName)
		}
	}

	if strings.TrimSpace(payload.BorrowerID) == "" {
		payload.BorrowerID = "user"
	}
	if strings.TrimSpace(payload.BorrowerName) == "" {
		payload.BorrowerName = payload.BorrowerID
	}
	if strings.TrimSpace(payload.ManagerID) == "" {
		payload.ManagerID = payload.BorrowerID
	}
	if strings.TrimSpace(payload.ManagerName) == "" {
		payload.ManagerName = payload.ManagerID
	}
	if strings.TrimSpace(payload.GroupName) == "" {
		payload.GroupName = "qtera mandiri"
	}

	// Availability validation: Check table assets, hold_borrow, and pending/active approval transactions
	_, borrowUserCompany := resolveUserContext(c)
	if borrowUserCompany == "" {
		borrowUserCompany = strings.TrimSpace(c.Get("X-Company"))
	}
	for _, it := range payload.Items {
		avail, errMsg := CheckAssetAvailability(ctx, it.AssetID, borrowUserCompany, "", "")
		if !avail {
			return c.Status(400).JSON(fiber.Map{"error": errMsg})
		}
	}

	// Generate transaction code TRX-BRW-XXX
	var nextNum int
	_ = DB.QueryRow(ctx, `
		SELECT COALESCE(MAX(SUBSTRING(transaction_code FROM 9)::int), 0) + 1
		FROM public.borrow_transactions
		WHERE transaction_code LIKE 'TRX-BRW-%'
	`).Scan(&nextNum)

	trxCode := fmt.Sprintf("TRX-BRW-%03d", nextNum)

	var trxID string
	err := DB.QueryRow(ctx, `
		INSERT INTO public.borrow_transactions (
			id, transaction_code, borrower_id, borrower_name, manager_id, manager_name, group_name, request_date, status, created_at
		) VALUES (
			gen_random_uuid(), $1, $2, $3, $4, $5, $6, CURRENT_DATE, 'pending_approval', NOW()
		) RETURNING id
	`, trxCode, payload.BorrowerID, payload.BorrowerName, payload.ManagerID, payload.ManagerName, payload.GroupName).Scan(&trxID)

	if err != nil {
		return c.Status(500).JSON(fiber.Map{"error": "Gagal menyimpan transaksi peminjaman: " + err.Error()})
	}

	for _, it := range payload.Items {
		dur := it.DurationDays
		if dur <= 0 {
			dur = 14
		}
		_, errItem := DB.Exec(ctx, `
			INSERT INTO public.borrow_items (
				id, transaction_id, asset_id, duration_days, status
			) VALUES (
				gen_random_uuid(), $1, $2, $3, 'pending'
			)
		`, trxID, it.AssetID, dur)
		if errItem != nil {
			log.Printf("[CreateBorrowRequest] Error inserting item %s: %v", it.AssetID, errItem)
		}
	}

	return c.Status(201).JSON(fiber.Map{
		"message":          "Permohonan peminjaman berhasil diajukan",
		"transaction_id":   trxID,
		"transaction_code": trxCode,
		"borrower_id":      payload.BorrowerID,
		"borrower_name":    payload.BorrowerName,
		"manager_id":       payload.ManagerID,
		"manager_name":     payload.ManagerName,
	})
}

// EnsureHoldBorrowTable bootstraps public.hold_borrow table and indices.
func EnsureHoldBorrowTable(ctx context.Context) error {
	if DB == nil {
		return fmt.Errorf("database connection pool is not initialized")
	}

	createTableSQL := `
	CREATE TABLE IF NOT EXISTS public.hold_borrow (
		id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
		hold_code VARCHAR(50) NOT NULL UNIQUE,
		borrower_id TEXT NOT NULL,
		borrower_name TEXT NOT NULL,
		manager_id TEXT NOT NULL,
		manager_name TEXT NOT NULL,
		group_name TEXT NOT NULL,
		items JSONB NOT NULL DEFAULT '[]'::jsonb,
		status VARCHAR(50) NOT NULL DEFAULT 'held',
		notes TEXT DEFAULT 'Created via AI Assistant',
		created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
		updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
	);

	CREATE INDEX IF NOT EXISTS idx_hold_borrow_status ON public.hold_borrow (status);
	CREATE INDEX IF NOT EXISTS idx_hold_borrow_group ON public.hold_borrow (group_name);
	CREATE INDEX IF NOT EXISTS idx_hold_borrow_borrower ON public.hold_borrow (borrower_id);
	CREATE INDEX IF NOT EXISTS idx_hold_borrow_created_at ON public.hold_borrow (created_at DESC);
	`

	_, err := DB.Exec(ctx, createTableSQL)
	if err != nil {
		log.Printf("[EnsureHoldBorrowTable] Failed to bootstrap public.hold_borrow: %v", err)
		return err
	}

	// Purge any rejected records so they don't clutter the system
	_, _ = DB.Exec(ctx, `DELETE FROM public.borrow_items WHERE transaction_id IN (SELECT id FROM public.borrow_transactions WHERE status = 'rejected')`)
	_, _ = DB.Exec(ctx, `DELETE FROM public.borrow_transactions WHERE status = 'rejected'`)
	_, _ = DB.Exec(ctx, `DELETE FROM public.hold_borrow WHERE status = 'rejected'`)

	log.Println("[EnsureHoldBorrowTable] Table public.hold_borrow verified successfully and rejected items purged.")
	return nil
}

type HoldBorrowItem struct {
	AssetID      string `json:"asset_id"`
	AssetName    string `json:"asset_name,omitempty"`
	Category     string `json:"category,omitempty"`
	DurationDays int    `json:"duration_days"`
}

type HoldBorrowRecord struct {
	ID           string           `json:"id"`
	HoldCode     string           `json:"hold_code"`
	BorrowerID   string           `json:"borrower_id"`
	BorrowerName string           `json:"borrower_name"`
	ManagerID    string           `json:"manager_id"`
	ManagerName  string           `json:"manager_name"`
	GroupName    string           `json:"group_name"`
	Items        []HoldBorrowItem `json:"items"`
	Status       string           `json:"status"`
	Notes        string           `json:"notes"`
	CreatedAt    time.Time        `json:"created_at"`
	UpdatedAt    time.Time        `json:"updated_at"`
}

// CheckAssetAvailability verifies:
// 1. Table public.assets: existence, tenant ownership, and availability status (not borrowed or maintenance)
// 2. Table public.hold_borrow: asset not currently held in unsubmitted queue (status = 'held')
// 3. Table public.borrow_transactions + borrow_items: asset not in pending_approval, approved, or active loan
func CheckAssetAvailability(ctx context.Context, assetID string, tenant string, excludeHoldID string, excludeTrxID string) (bool, string) {
	assetID = strings.TrimSpace(assetID)
	if assetID == "" {
		return false, "Asset ID tidak boleh kosong"
	}

	// 1. Cek tabel public.assets
	var aName, aStatus, aPerusahaan string
	err := DB.QueryRow(ctx, `
		SELECT name, COALESCE(status, 'available'), COALESCE(perusahaan, '')
		FROM public.assets
		WHERE asset_id ILIKE $1
		LIMIT 1
	`, assetID).Scan(&aName, &aStatus, &aPerusahaan)
	if err != nil {
		return false, fmt.Sprintf("Aset '%s' tidak ditemukan dalam database aset", assetID)
	}

	if tenant != "" && aPerusahaan != "" && !strings.EqualFold(aPerusahaan, tenant) {
		return false, fmt.Sprintf("Aset '%s' (%s) terdaftar pada tenant '%s', tidak dapat dipinjam oleh tenant '%s'", assetID, aName, aPerusahaan, tenant)
	}

	if strings.EqualFold(aStatus, "borrowed") {
		return false, fmt.Sprintf("Aset '%s' (%s) saat ini sedang berstatus DIPINJAM", assetID, aName)
	}
	if strings.EqualFold(aStatus, "maintenance") || strings.EqualFold(aStatus, "rusak") {
		return false, fmt.Sprintf("Aset '%s' (%s) sedang dalam status '%s'", assetID, aName, aStatus)
	}

	// 2. Cek tabel public.hold_borrow (apakah sedang dalam antrean hold yang belum submit)
	holdQuery := `
		SELECT h.hold_code, h.borrower_name
		FROM public.hold_borrow h
		WHERE h.status = 'held'
		  AND h.items::text ILIKE '%' || $1 || '%'
	`
	var holdArgs = []any{assetID}
	if excludeHoldID != "" {
		holdQuery += " AND h.id::text != $2 AND h.hold_code != $2"
		holdArgs = append(holdArgs, excludeHoldID)
	}
	holdQuery += " LIMIT 1"

	var holdCode, holdBorrower string
	if errHold := DB.QueryRow(ctx, holdQuery, holdArgs...).Scan(&holdCode, &holdBorrower); errHold == nil && holdCode != "" {
		return false, fmt.Sprintf("Aset '%s' (%s) saat ini sedang di-hold oleh %s (kode hold: %s)", assetID, aName, holdBorrower, holdCode)
	}

	// 3. Cek tabel public.borrow_transactions + public.borrow_items (apakah sedang pending_approval / active)
	trxQuery := `
		SELECT t.transaction_code, t.borrower_name, t.status
		FROM public.borrow_items bi
		JOIN public.borrow_transactions t ON bi.transaction_id = t.id
		WHERE bi.asset_id ILIKE $1
		  AND COALESCE(bi.status, '') != 'rejected'
		  AND t.status IN ('pending_approval', 'approved', 'active')
	`
	var trxArgs = []any{assetID}
	if excludeTrxID != "" {
		trxQuery += " AND t.id::text != $2 AND t.transaction_code != $2"
		trxArgs = append(trxArgs, excludeTrxID)
	}
	trxQuery += " LIMIT 1"

	var trxCode, trxBorrower, trxStatus string
	if errTrx := DB.QueryRow(ctx, trxQuery, trxArgs...).Scan(&trxCode, &trxBorrower, &trxStatus); errTrx == nil && trxCode != "" {
		statusLabel := "menunggu approval"
		if trxStatus == "active" {
			statusLabel = "sedang aktif dipinjam"
		} else if trxStatus == "approved" {
			statusLabel = "telah disetujui"
		}
		return false, fmt.Sprintf("Aset '%s' (%s) %s dalam transaksi %s oleh %s", assetID, aName, statusLabel, trxCode, trxBorrower)
	}

	return true, ""
}

// CreateHoldBorrowRequest creates a pending hold_borrow record (AI-created borrow requests are held here)
func CreateHoldBorrowRequest(c *fiber.Ctx) error {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	var payload struct {
		BorrowerID   string           `json:"borrower_id"`
		BorrowerName string           `json:"borrower_name"`
		GroupName    string           `json:"group_name"`
		ManagerID    string           `json:"manager_id"`
		ManagerName  string           `json:"manager_name"`
		Items        []HoldBorrowItem `json:"items"`
		Notes        string           `json:"notes"`
	}

	if err := c.BodyParser(&payload); err != nil {
		return c.Status(400).JSON(fiber.Map{"error": "Invalid request body"})
	}

	if strings.TrimSpace(payload.BorrowerName) == "" && strings.TrimSpace(payload.BorrowerID) == "" {
		return c.Status(400).JSON(fiber.Map{"error": "Nama peminjam atau borrower_id wajib diisi"})
	}
	if len(payload.Items) == 0 {
		return c.Status(400).JSON(fiber.Map{"error": "Minimal 1 aset harus dipilih"})
	}

	// 1. Manager credentials resolution
	if strings.TrimSpace(payload.ManagerID) == "" {
		if id := middleware.RequestIdentity(c); id != nil && id.UserID != "" {
			payload.ManagerID = id.UserID
		} else if uid := c.Get("X-User-ID"); uid != "" {
			payload.ManagerID = uid
		}
	}
	if strings.TrimSpace(payload.ManagerName) == "" {
		if id := middleware.RequestIdentity(c); id != nil && id.Username != "" {
			payload.ManagerName = id.Username
		} else if uname := c.Get("X-User-Name"); uname != "" {
			payload.ManagerName = uname
		} else if uname := c.Get("X-Username"); uname != "" {
			payload.ManagerName = uname
		} else if payload.ManagerID != "" {
			payload.ManagerName = payload.ManagerID
		}
	}

	// 2. Borrower resolution: Fetch borrower_id from DB based on borrower_name (take 1)
	if strings.TrimSpace(payload.BorrowerName) == "" && strings.TrimSpace(payload.BorrowerID) != "" {
		payload.BorrowerName = payload.BorrowerID
	}
	if strings.TrimSpace(payload.BorrowerName) != "" {
		bName := strings.TrimSpace(payload.BorrowerName)
		uID, uName, uCompany, found := ResolveUserByBorrowerName(ctx, bName)
		if uID != "" {
			payload.BorrowerID = uID
			if found && uName != "" {
				payload.BorrowerName = uName
			}
			if uCompany != "" && (payload.GroupName == "" || payload.GroupName == "qtera mandiri") {
				payload.GroupName = uCompany
			}
			log.Printf("[CreateHoldBorrowRequest] Resolved borrower_id=%s (users.id) for borrower_name=%s", payload.BorrowerID, payload.BorrowerName)
		}
	}

	if strings.TrimSpace(payload.BorrowerID) == "" {
		payload.BorrowerID = "user"
	}
	if strings.TrimSpace(payload.BorrowerName) == "" {
		payload.BorrowerName = payload.BorrowerID
	}
	if strings.TrimSpace(payload.ManagerID) == "" {
		payload.ManagerID = payload.BorrowerID
	}
	if strings.TrimSpace(payload.ManagerName) == "" {
		payload.ManagerName = payload.ManagerID
	}
	if strings.TrimSpace(payload.GroupName) == "" {
		payload.GroupName = "qtera mandiri"
	}
	if strings.TrimSpace(payload.Notes) == "" {
		payload.Notes = "Dibuat otomatis oleh AI Assistant"
	}

	// Availability validation: Check table assets, hold_borrow, and pending/active approval transactions
	_, holdUserCompany := resolveUserContext(c)
	if holdUserCompany == "" {
		holdUserCompany = strings.TrimSpace(c.Get("X-Company"))
	}
	for _, it := range payload.Items {
		avail, errMsg := CheckAssetAvailability(ctx, it.AssetID, holdUserCompany, "", "")
		if !avail {
			return c.Status(400).JSON(fiber.Map{"error": errMsg})
		}
	}

	// Enrich items with asset name & category from DB
	for i := range payload.Items {
		if payload.Items[i].DurationDays <= 0 {
			payload.Items[i].DurationDays = 14
		}
		var aName, aCat string
		_ = DB.QueryRow(ctx, `SELECT name, category FROM public.assets WHERE asset_id ILIKE $1 LIMIT 1`, payload.Items[i].AssetID).Scan(&aName, &aCat)
		if aName != "" {
			payload.Items[i].AssetName = aName
		}
		if aCat != "" {
			payload.Items[i].Category = aCat
		}
	}

	itemsJSON, err := json.Marshal(payload.Items)
	if err != nil {
		itemsJSON = []byte("[]")
	}

	// Generate code HOLD-BRW-XXX
	var nextNum int
	_ = DB.QueryRow(ctx, `
		SELECT COALESCE(MAX(SUBSTRING(hold_code FROM 10)::int), 0) + 1
		FROM public.hold_borrow
		WHERE hold_code LIKE 'HOLD-BRW-%'
	`).Scan(&nextNum)

	holdCode := fmt.Sprintf("HOLD-BRW-%03d", nextNum)

	var holdID string
	err = DB.QueryRow(ctx, `
		INSERT INTO public.hold_borrow (
			id, hold_code, borrower_id, borrower_name, manager_id, manager_name, group_name, items, status, notes, created_at, updated_at
		) VALUES (
			gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7, 'held', $8, NOW(), NOW()
		) RETURNING id
	`, holdCode, payload.BorrowerID, payload.BorrowerName, payload.ManagerID, payload.ManagerName, payload.GroupName, itemsJSON, payload.Notes).Scan(&holdID)

	if err != nil {
		return c.Status(500).JSON(fiber.Map{"error": "Gagal menyimpan permohonan ke hold_borrow: " + err.Error()})
	}

	return c.Status(201).JSON(fiber.Map{
		"message":          "Permohonan peminjaman berhasil dicatat dan ditahan di antrean Hold Borrow. Silakan lakukan submit manual di halaman Approve Hold Borrow untuk memprosesnya.",
		"hold_id":          holdID,
		"hold_code":        holdCode,
		"status":           "held",
		"borrower_id":      payload.BorrowerID,
		"borrower_name":    payload.BorrowerName,
		"manager_id":       payload.ManagerID,
		"manager_name":     payload.ManagerName,
		"group_name":       payload.GroupName,
		"items":            payload.Items,
	})
}

// GetHoldBorrowList retrieves held borrow requests
func GetHoldBorrowList(c *fiber.Ctx) error {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	_, userCompany := resolveUserContext(c)
	if userCompany == "" {
		userCompany = strings.TrimSpace(c.Get("X-Company"))
	}
	status := strings.TrimSpace(c.Query("status"))
	groupName := strings.TrimSpace(c.Query("group_name"))

	query := `
		SELECT h.id, h.hold_code, h.borrower_id, h.borrower_name, h.manager_id, h.manager_name, h.group_name, h.items, h.status, COALESCE(h.notes, ''), h.created_at, h.updated_at
		FROM public.hold_borrow h
		LEFT JOIN public.users u ON (h.borrower_id = u.id OR LOWER(h.borrower_name) = LOWER(u.username))
		WHERE h.status != 'rejected'
	`
	args := []any{}
	argIdx := 1

	if status != "" && !strings.EqualFold(status, "all") {
		query += fmt.Sprintf(" AND h.status = $%d", argIdx)
		args = append(args, status)
		argIdx++
	} else if status == "" {
		// By default show 'held' requests
		query += fmt.Sprintf(" AND h.status = $%d", argIdx)
		args = append(args, "held")
		argIdx++
	}

	// Strict Tenant Isolation for Hold list
	if userCompany != "" {
		query += fmt.Sprintf(` AND (
			LOWER(TRIM(u.company)) = LOWER(TRIM($%d))
			OR LOWER(TRIM(h.group_name)) = LOWER(TRIM($%d))
			OR EXISTS (
				SELECT 1 FROM public.assets a 
				WHERE LOWER(TRIM(a.perusahaan)) = LOWER(TRIM($%d))
				  AND h.items::text ILIKE '%%' || a.asset_id || '%%'
			)
		)`, argIdx, argIdx, argIdx)
		args = append(args, userCompany)
		argIdx++
	}

	if groupName != "" {
		query += fmt.Sprintf(" AND LOWER(h.group_name) = LOWER($%d)", argIdx)
		args = append(args, groupName)
		argIdx++
	}

	query += " ORDER BY created_at DESC"

	rows, err := DB.Query(ctx, query, args...)
	if err != nil {
		return c.Status(500).JSON(fiber.Map{"error": "Gagal mengambil daftar hold borrow: " + err.Error()})
	}
	defer rows.Close()

	var results []HoldBorrowRecord
	for rows.Next() {
		var r HoldBorrowRecord
		var itemsRaw []byte
		if err := rows.Scan(&r.ID, &r.HoldCode, &r.BorrowerID, &r.BorrowerName, &r.ManagerID, &r.ManagerName, &r.GroupName, &itemsRaw, &r.Status, &r.Notes, &r.CreatedAt, &r.UpdatedAt); err == nil {
			if len(itemsRaw) > 0 {
				_ = json.Unmarshal(itemsRaw, &r.Items)
			}
			results = append(results, r)
		}
	}

	if results == nil {
		results = []HoldBorrowRecord{}
	}

	return c.JSON(fiber.Map{
		"data":  results,
		"total": len(results),
	})
}

// GetHoldBorrowDetail retrieves a single hold_borrow record by ID or hold_code
func GetHoldBorrowDetail(c *fiber.Ctx) error {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	id := strings.TrimSpace(c.Params("id"))
	if id == "" {
		return c.Status(400).JSON(fiber.Map{"error": "ID or hold_code is required"})
	}

	var r HoldBorrowRecord
	var itemsRaw []byte
	err := DB.QueryRow(ctx, `
		SELECT id, hold_code, borrower_id, borrower_name, manager_id, manager_name, group_name, items, status, COALESCE(notes, ''), created_at, updated_at
		FROM public.hold_borrow
		WHERE id::text = $1 OR hold_code = $1
		LIMIT 1
	`, id).Scan(&r.ID, &r.HoldCode, &r.BorrowerID, &r.BorrowerName, &r.ManagerID, &r.ManagerName, &r.GroupName, &itemsRaw, &r.Status, &r.Notes, &r.CreatedAt, &r.UpdatedAt)

	if err != nil {
		return c.Status(404).JSON(fiber.Map{"error": "Permohonan hold borrow tidak ditemukan"})
	}
	if len(itemsRaw) > 0 {
		_ = json.Unmarshal(itemsRaw, &r.Items)
	}

	return c.JSON(r)
}

// UpdateHoldBorrowPayload represents fields that can be edited in a held borrow request
type UpdateHoldBorrowPayload struct {
	BorrowerName string           `json:"borrower_name"`
	BorrowerID   string           `json:"borrower_id"`
	GroupName    string           `json:"group_name"`
	Notes        string           `json:"notes"`
	Items        []HoldBorrowItem `json:"items"`
}

// UpdateHoldBorrow updates editable fields of a held borrow request before confirmation
func UpdateHoldBorrow(c *fiber.Ctx) error {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	id := strings.TrimSpace(c.Params("id"))
	if id == "" {
		return c.Status(400).JSON(fiber.Map{"error": "ID or hold_code is required"})
	}

	var payload UpdateHoldBorrowPayload
	if err := c.BodyParser(&payload); err != nil {
		return c.Status(400).JSON(fiber.Map{"error": "Format request tidak valid: " + err.Error()})
	}

	// 1. Fetch current record
	var currentStatus, currentBorrowerID, currentBorrowerName, currentGroupName, currentNotes string
	var currentItemsRaw []byte
	err := DB.QueryRow(ctx, `
		SELECT status, borrower_id, borrower_name, group_name, notes, items
		FROM public.hold_borrow
		WHERE id::text = $1 OR hold_code = $1
		LIMIT 1
	`, id).Scan(&currentStatus, &currentBorrowerID, &currentBorrowerName, &currentGroupName, &currentNotes, &currentItemsRaw)

	if err != nil {
		return c.Status(404).JSON(fiber.Map{"error": "Permohonan hold borrow tidak ditemukan"})
	}

	if currentStatus != "held" {
		return c.Status(400).JSON(fiber.Map{"error": fmt.Sprintf("Permohonan hold tidak dapat diedit karena statusnya sudah '%s'", currentStatus)})
	}

	// 2. Resolve updated fields
	newBorrowerName := strings.TrimSpace(payload.BorrowerName)
	if newBorrowerName == "" {
		newBorrowerName = currentBorrowerName
	}

	newBorrowerID := strings.TrimSpace(payload.BorrowerID)
	// If borrower name changed or borrower ID is empty, resolve user ID
	if newBorrowerName != currentBorrowerName || newBorrowerID == "" {
		uID, uName, uCompany, found := ResolveUserByBorrowerName(ctx, newBorrowerName)
		if uID != "" {
			newBorrowerID = uID
			if found && uName != "" {
				newBorrowerName = uName
			}
			if uCompany != "" && strings.TrimSpace(payload.GroupName) == "" {
				payload.GroupName = uCompany
			}
		} else if newBorrowerID == "" {
			newBorrowerID = currentBorrowerID
		}
	}

	newGroupName := strings.TrimSpace(payload.GroupName)
	if newGroupName == "" {
		newGroupName = currentGroupName
	}

	newNotes := strings.TrimSpace(payload.Notes)
	if newNotes == "" {
		newNotes = currentNotes
	}

	var newItems []HoldBorrowItem
	if payload.Items != nil {
		if len(payload.Items) == 0 {
			return c.Status(400).JSON(fiber.Map{"error": "Permohonan hold minimal harus memiliki 1 aset"})
		}
		for i := range payload.Items {
			it := payload.Items[i]
			it.AssetID = strings.TrimSpace(it.AssetID)
			if it.AssetID == "" {
				continue
			}
			if it.DurationDays <= 0 {
				it.DurationDays = 14
			}
			// Enrich asset name and category if missing
			if it.AssetName == "" || it.Category == "" {
				var aName, aCat string
				_ = DB.QueryRow(ctx, `SELECT name, category FROM public.assets WHERE asset_id ILIKE $1 LIMIT 1`, it.AssetID).Scan(&aName, &aCat)
				if it.AssetName == "" && aName != "" {
					it.AssetName = aName
				}
				if it.Category == "" && aCat != "" {
					it.Category = aCat
				}
			}
			newItems = append(newItems, it)
		}
		if len(newItems) == 0 {
			return c.Status(400).JSON(fiber.Map{"error": "Minimal 1 aset yang valid harus dicantumkan"})
		}
	} else {
		if len(currentItemsRaw) > 0 {
			_ = json.Unmarshal(currentItemsRaw, &newItems)
		}
	}

	newItemsJSON, err := json.Marshal(newItems)
	if err != nil {
		newItemsJSON = []byte("[]")
	}

	// 3. Update DB
	var updatedRecord HoldBorrowRecord
	var updatedItemsRaw []byte
	err = DB.QueryRow(ctx, `
		UPDATE public.hold_borrow
		SET borrower_id = $1,
		    borrower_name = $2,
		    group_name = $3,
		    notes = $4,
		    items = $5,
		    updated_at = NOW()
		WHERE id::text = $6 OR hold_code = $6
		RETURNING id, hold_code, borrower_id, borrower_name, manager_id, manager_name, group_name, items, status, COALESCE(notes, ''), created_at, updated_at
	`, newBorrowerID, newBorrowerName, newGroupName, newNotes, newItemsJSON, id).Scan(
		&updatedRecord.ID, &updatedRecord.HoldCode, &updatedRecord.BorrowerID, &updatedRecord.BorrowerName,
		&updatedRecord.ManagerID, &updatedRecord.ManagerName, &updatedRecord.GroupName, &updatedItemsRaw,
		&updatedRecord.Status, &updatedRecord.Notes, &updatedRecord.CreatedAt, &updatedRecord.UpdatedAt,
	)

	if err != nil {
		return c.Status(500).JSON(fiber.Map{"error": "Gagal memperbarui permohonan hold: " + err.Error()})
	}

	if len(updatedItemsRaw) > 0 {
		_ = json.Unmarshal(updatedItemsRaw, &updatedRecord.Items)
	}

	return c.JSON(fiber.Map{
		"message": "Data permohonan hold peminjaman berhasil diperbarui",
		"data":    updatedRecord,
	})
}

// SubmitHoldBorrow manually submits a held borrow record into official borrow_transactions
func SubmitHoldBorrow(c *fiber.Ctx) error {
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	id := strings.TrimSpace(c.Params("id"))
	if id == "" {
		return c.Status(400).JSON(fiber.Map{"error": "ID or hold_code is required"})
	}

	var r HoldBorrowRecord
	var itemsRaw []byte
	err := DB.QueryRow(ctx, `
		SELECT id, hold_code, borrower_id, borrower_name, manager_id, manager_name, group_name, items, status, COALESCE(notes, ''), created_at, updated_at
		FROM public.hold_borrow
		WHERE id::text = $1 OR hold_code = $1
		LIMIT 1
	`, id).Scan(&r.ID, &r.HoldCode, &r.BorrowerID, &r.BorrowerName, &r.ManagerID, &r.ManagerName, &r.GroupName, &itemsRaw, &r.Status, &r.Notes, &r.CreatedAt, &r.UpdatedAt)

	if err != nil {
		return c.Status(404).JSON(fiber.Map{"error": "Permohonan hold borrow tidak ditemukan"})
	}

	if r.Status != "held" {
		return c.Status(400).JSON(fiber.Map{"error": fmt.Sprintf("Permohonan hold ini tidak dapat di-submit karena statusnya '%s'", r.Status)})
	}

	if len(itemsRaw) > 0 {
		_ = json.Unmarshal(itemsRaw, &r.Items)
	}

	// Check if body contains updated fields upon confirmation
	var payload UpdateHoldBorrowPayload
	if errBody := c.BodyParser(&payload); errBody == nil {
		if strings.TrimSpace(payload.BorrowerName) != "" {
			r.BorrowerName = strings.TrimSpace(payload.BorrowerName)
			uID, uName, uCompany, found := ResolveUserByBorrowerName(ctx, r.BorrowerName)
			if uID != "" {
				r.BorrowerID = uID
				if found && uName != "" {
					r.BorrowerName = uName
				}
				if uCompany != "" && strings.TrimSpace(payload.GroupName) == "" {
					r.GroupName = uCompany
				}
			}
		}
		if strings.TrimSpace(payload.GroupName) != "" {
			r.GroupName = strings.TrimSpace(payload.GroupName)
		}
		if strings.TrimSpace(payload.Notes) != "" {
			r.Notes = strings.TrimSpace(payload.Notes)
		}
		if len(payload.Items) > 0 {
			var validItems []HoldBorrowItem
			for _, it := range payload.Items {
				it.AssetID = strings.TrimSpace(it.AssetID)
				if it.AssetID == "" {
					continue
				}
				if it.DurationDays <= 0 {
					it.DurationDays = 14
				}
				if it.AssetName == "" || it.Category == "" {
					var aName, aCat string
					_ = DB.QueryRow(ctx, `SELECT name, category FROM public.assets WHERE asset_id ILIKE $1 LIMIT 1`, it.AssetID).Scan(&aName, &aCat)
					if it.AssetName == "" && aName != "" {
						it.AssetName = aName
					}
					if it.Category == "" && aCat != "" {
						it.Category = aCat
					}
				}
				validItems = append(validItems, it)
			}
			if len(validItems) > 0 {
				r.Items = validItems
			}
		}
	}

	if len(r.Items) == 0 {
		return c.Status(400).JSON(fiber.Map{"error": "Permohonan tidak memiliki aset yang dipinjam"})
	}

	// Availability validation: Check table assets, other hold_borrow, and pending/active approval transactions
	_, submitUserCompany := resolveUserContext(c)
	if submitUserCompany == "" {
		submitUserCompany = strings.TrimSpace(c.Get("X-Company"))
	}
	for _, it := range r.Items {
		avail, errMsg := CheckAssetAvailability(ctx, it.AssetID, submitUserCompany, r.ID, "")
		if !avail {
			return c.Status(400).JSON(fiber.Map{"error": errMsg})
		}
	}

	// 1. Generate transaction code TRX-BRW-XXX
	var nextNum int
	_ = DB.QueryRow(ctx, `
		SELECT COALESCE(MAX(SUBSTRING(transaction_code FROM 9)::int), 0) + 1
		FROM public.borrow_transactions
		WHERE transaction_code LIKE 'TRX-BRW-%'
	`).Scan(&nextNum)

	trxCode := fmt.Sprintf("TRX-BRW-%03d", nextNum)

	// 2. Insert into public.borrow_transactions
	var trxID string
	err = DB.QueryRow(ctx, `
		INSERT INTO public.borrow_transactions (
			id, transaction_code, borrower_id, borrower_name, manager_id, manager_name, group_name, request_date, status, created_at
		) VALUES (
			gen_random_uuid(), $1, $2, $3, $4, $5, $6, CURRENT_DATE, 'pending_approval', NOW()
		) RETURNING id
	`, trxCode, r.BorrowerID, r.BorrowerName, r.ManagerID, r.ManagerName, r.GroupName).Scan(&trxID)

	if err != nil {
		return c.Status(500).JSON(fiber.Map{"error": "Gagal membuat transaksi peminjaman resmi: " + err.Error()})
	}

	// 3. Insert items into public.borrow_items
	for _, it := range r.Items {
		dur := it.DurationDays
		if dur <= 0 {
			dur = 14
		}
		var realAssetID string
		_ = DB.QueryRow(ctx, `SELECT asset_id FROM public.assets WHERE asset_id ILIKE $1 LIMIT 1`, it.AssetID).Scan(&realAssetID)
		if realAssetID != "" {
			it.AssetID = realAssetID
		}
		_, errItem := DB.Exec(ctx, `
			INSERT INTO public.borrow_items (
				id, transaction_id, asset_id, duration_days, status
			) VALUES (
				gen_random_uuid(), $1, $2, $3, 'pending'
			)
		`, trxID, it.AssetID, dur)
		if errItem != nil {
			log.Printf("[SubmitHoldBorrow] Error inserting item %s: %v", it.AssetID, errItem)
		}
	}

	// 4. Update status in public.hold_borrow to 'submitted' with latest items and notes
	finalItemsJSON, _ := json.Marshal(r.Items)
	newNotes := strings.TrimSpace(r.Notes + " [Submitted as " + trxCode + "]")
	_, _ = DB.Exec(ctx, `
		UPDATE public.hold_borrow
		SET status = 'submitted', borrower_id = $1, borrower_name = $2, group_name = $3, items = $4, notes = $5, updated_at = NOW()
		WHERE id = $6
	`, r.BorrowerID, r.BorrowerName, r.GroupName, finalItemsJSON, newNotes, r.ID)

	return c.Status(200).JSON(fiber.Map{
		"message":          "Permohonan peminjaman berhasil di-submit ke sistem transaksi!",
		"hold_code":        r.HoldCode,
		"transaction_id":   trxID,
		"transaction_code": trxCode,
		"borrower_name":    r.BorrowerName,
		"items_count":      len(r.Items),
	})
}

// RejectHoldBorrow deletes a held borrow request so it doesn't clutter the page
func RejectHoldBorrow(c *fiber.Ctx) error {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	id := strings.TrimSpace(c.Params("id"))
	if id == "" {
		return c.Status(400).JSON(fiber.Map{"error": "ID or hold_code is required"})
	}

	_, err := DB.Exec(ctx, `DELETE FROM public.hold_borrow WHERE id::text = $1 OR hold_code = $1`, id)
	if err != nil {
		return c.Status(500).JSON(fiber.Map{"error": "Gagal menghapus hold borrow: " + err.Error()})
	}

	return c.JSON(fiber.Map{
		"message": "Permohonan hold peminjaman berhasil ditolak dan dihapus",
		"status":  "deleted",
	})
}

// RestoreHoldBorrow restores a rejected hold borrow back to 'held'
func RestoreHoldBorrow(c *fiber.Ctx) error {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	id := strings.TrimSpace(c.Params("id"))
	if id == "" {
		return c.Status(400).JSON(fiber.Map{"error": "ID or hold_code is required"})
	}

	_, err := DB.Exec(ctx, `UPDATE public.hold_borrow SET status = 'held', updated_at = NOW() WHERE id::text = $1 OR hold_code = $1`, id)
	if err != nil {
		return c.Status(500).JSON(fiber.Map{"error": "Gagal memulihkan hold borrow: " + err.Error()})
	}

	return c.JSON(fiber.Map{
		"message": "Permohonan hold peminjaman berhasil dipulihkan ke status Menunggu Submit",
		"status":  "held",
	})
}

